import { useState, useCallback } from "react";

const FLAG_URLS = {
  FRA:"https://flagcdn.com/w40/fr.png", ARG:"https://flagcdn.com/w40/ar.png",
  ESP:"https://flagcdn.com/w40/es.png", ENG:"https://flagcdn.com/w40/gb-eng.png",
  BRA:"https://flagcdn.com/w40/br.png", GER:"https://flagcdn.com/w40/de.png",
  POR:"https://flagcdn.com/w40/pt.png", MAR:"https://flagcdn.com/w40/ma.png",
  NED:"https://flagcdn.com/w40/nl.png", URU:"https://flagcdn.com/w40/uy.png",
  BEL:"https://flagcdn.com/w40/be.png", JPN:"https://flagcdn.com/w40/jp.png",
  MEX:"https://flagcdn.com/w40/mx.png", CAN:"https://flagcdn.com/w40/ca.png",
  USA:"https://flagcdn.com/w40/us.png", KOR:"https://flagcdn.com/w40/kr.png",
  COL:"https://flagcdn.com/w40/co.png", TUR:"https://flagcdn.com/w40/tr.png",
  NOR:"https://flagcdn.com/w40/no.png", SEN:"https://flagcdn.com/w40/sn.png",
  CRO:"https://flagcdn.com/w40/hr.png", SWE:"https://flagcdn.com/w40/se.png",
  EGY:"https://flagcdn.com/w40/eg.png", AUT:"https://flagcdn.com/w40/at.png",
  SUI:"https://flagcdn.com/w40/ch.png", GHA:"https://flagcdn.com/w40/gh.png",
  CIV:"https://flagcdn.com/w40/ci.png", SCO:"https://flagcdn.com/w40/gb-sct.png",
  ECU:"https://flagcdn.com/w40/ec.png", PAR:"https://flagcdn.com/w40/py.png",
  AUS:"https://flagcdn.com/w40/au.png", CPV:"https://flagcdn.com/w40/cv.png",
  IRQ:"https://flagcdn.com/w40/iq.png", ALG:"https://flagcdn.com/w40/dz.png",
  JOR:"https://flagcdn.com/w40/jo.png", KSA:"https://flagcdn.com/w40/sa.png",
  IRN:"https://flagcdn.com/w40/ir.png", QAT:"https://flagcdn.com/w40/qa.png",
  CZE:"https://flagcdn.com/w40/cz.png", RSA:"https://flagcdn.com/w40/za.png",
  BIH:"https://flagcdn.com/w40/ba.png", NZL:"https://flagcdn.com/w40/nz.png",
  HAI:"https://flagcdn.com/w40/ht.png", PAN:"https://flagcdn.com/w40/pa.png",
  CUR:"https://flagcdn.com/w40/cw.png", UZB:"https://flagcdn.com/w40/uz.png",
  COD:"https://flagcdn.com/w40/cd.png", TUN:"https://flagcdn.com/w40/tn.png",
};

export function Flag({id, size=24, style={}}){
  const url = FLAG_URLS[id];
  if(!url) return null;
  return <img src={url} alt={id} style={{width:size,height:"auto",borderRadius:2,objectFit:"cover",flexShrink:0,...style}} />;
}

export const INITIAL_TEAMS = [
  { id:"FRA", flag:"🇫🇷", name:"France",      group:"I", prob:18, peak:18, manager:"Deschamps",   cis:9.1, form:9, chemistry:8.9, change:0,
    strengths:"#1 FIFA ranked. Deepest squad in tournament. Deschamps 14-year tenure. Mbappé, Tchouaméni, Griezmann, Saliba, Theo Hernández all in peak form. Dembélé (Ballon d'Or 2025), Olise (41 goals+46 assists at Bayern), and Doué form explosive wide attacking trio. Perfect age balance.",
    weaknesses:"Confirmed absences of Ekitike and Kamara. Deschamps' conservatism can stall against deep blocks. Front-loaded attack can leave midfield transition cover exposed.",
    rationale:"France leads because no team combines system depth, managerial experience, big-game record, and squad chemistry at the same level. Dembélé as Ballon d'Or winner and Olise's output make this the most dangerous attack at the tournament."
  },
  { id:"ARG", flag:"🇦🇷", name:"Argentina",   group:"J", prob:15, peak:15, manager:"Scaloni",    cis:9.4, form:8, chemistry:9.2, change:0,
    strengths:"Highest Chemistry Score (9.2/10) and Manager CIS (9.4/10). Scaloni's 7+ years. Mac Allister, Enzo Fernández, De Paul — most rehearsed midfield trio. Reigning champions. Lautaro and J. Álvarez elite striker depth.",
    weaknesses:"Messi at 38 — physical availability across 8 matches is a concern. Romero and Molina fitness doubts. Lisandro Martínez likely third-choice CB. Squad skewed older.",
    rationale:"Argentina's team cohesion is unmatched but age-related fatigue risk and key injury doubts prevent them reaching France's probability ceiling."
  },
  { id:"ESP", flag:"🇪🇸", name:"Spain",       group:"H", prob:14, peak:14, manager:"De la Fuente",cis:8.7, form:9, chemistry:8.6, change:0,
    strengths:"Euro 2024 and Nations League winners. Rodri-Pedri axis. Oyarzabal — scored in all 6 career finals. Yamal, Dani Olmo explosive. Highest competitive win rate (74%) of any manager.",
    weaknesses:"Samu Omorodion and Fermín López out. Yamal fitness race after late-April hamstring injury. Defensive depth behind first-choice CB pairing is thin.",
    rationale:"Spain's form and system are exceptional but Yamal injury uncertainty and confirmed striker absences cap their probability just below Argentina."
  },
  { id:"ENG", flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", name:"England",    group:"L", prob:11, peak:11, manager:"Tuchel",      cis:7.8, form:8, chemistry:7.4, change:0,
    strengths:"Kane, Bellingham, Saka, Eze, Declan Rice, Marc Guéhi, Reece James. Most PL players of any squad. Tuchel's CL pedigree resolves structural fragility. No loss to top-10 nation in last 9 competitive matches.",
    weaknesses:"Tuchel only 2 years in — system still building. Foden and Palmer not selected for the squad. Ben White and Grealish absent. Set-piece defence historically vulnerable.",
    rationale:"England's individual quality and big-game record are elite, but Foden/Palmer absences and 2 years of system-building leave a creative ceiling gap vs France/Spain."
  },
  { id:"BRA", flag:"🇧🇷", name:"Brazil",      group:"C", prob:9, peak:9, manager:"Ancelotti",  cis:7.4, form:7, chemistry:7.1, change:0,
    strengths:"Vinicius Jr in extraordinary form. João Pedro (14 PL goals for Chelsea) as the #9. Raphinha (50+ Barcelona goals in 2 seasons). Six scorers in Panama warmup. Ancelotti's 4× CL pedigree.",
    weaknesses:"Rodrygo (ACL), Militão (hamstring), Estêvão all confirmed out. Neymar absent for opener. Ancelotti only 2 years in. Largest injury burden of any top-8 side. Chemistry Score only 7.1/10.",
    rationale:"Brazil's ceiling is world-class but their floor has dropped significantly due to the most significant injury crisis of any contender."
  },
  { id:"GER", flag:"🇩🇪", name:"Germany",     group:"E", prob:8, peak:8, manager:"Nagelsmann", cis:7.5, form:8, chemistry:7.3, change:0,
    strengths:"8-match winning streak. Wirtz-Musiala creative axis. Lennart Karl emerging as third attacking star. Dominant possession metrics. Proactive pressing system.",
    weaknesses:"Gnabry and ter Stegen both out. Undav injury concern from Finland warmup. No major international trophy yet under Nagelsmann.",
    rationale:"Germany's form trajectory and Wirtz-Musiala combination make them a genuine semi-final threat, but managerial inexperience and injury concerns limit their ceiling."
  },
  { id:"POR", flag:"🇵🇹", name:"Portugal",    group:"K", prob:7, peak:7, manager:"Martínez",   cis:7.6, form:8, chemistry:7.8, change:0,
    strengths:"2025 Nations League winners. Ronaldo, Bruno Fernandes, Bernardo Silva, Vitinha, João Neves, Leão, Gonçalo Ramos. João Cancelo attacking threat from right back.",
    weaknesses:"Ronaldo at 41 creates structural distortions. No significant trophy since 2016 despite quality. Knockout-stage fragility historically persistent.",
    rationale:"Portugal's individual quality is top-5 but Ronaldo-dependency and knockout fragility prevent matching France or Spain's overall probability."
  },
  { id:"MAR", flag:"🇲🇦", name:"Morocco",     group:"C", prob:5, peak:5, manager:"Regragui",   cis:8.2, form:8, chemistry:8.4, change:0,
    strengths:"21-match unbeaten streak. Five clean sheets in last six. Hakimi expected fit. Saibari, Rahimi, El Kaabi, Khannouss in form. Deeply embedded defensive system.",
    weaknesses:"Attacking depth beyond first XI limited. Fitness under 8-match tournament pressure historically their ceiling.",
    rationale:"Morocco are the tournament's most dangerous defensive unit and most likely team to produce a knockout upset. Offensive ceiling caps outright probability."
  },
  { id:"NED", flag:"🇳🇱", name:"Netherlands", group:"F", prob:4, peak:4, manager:"Koeman",     cis:6.8, form:7, chemistry:6.5, change:0,
    strengths:"Van Dijk's defensive leadership. Dumfries and Frimpong (Liverpool) elite wing-back threat. Gakpo pace and directness.",
    weaknesses:"Xavi Simons (ACL) and Matthijs de Ligt both out. Algeria warmup loss (0-1) exposed creativity issues. Chemistry Score only 6.5/10.",
    rationale:"Netherlands have the defensive quality to go far but the double injury loss of their two most dynamic players reduces them to dangerous outsider."
  },
  { id:"URU", flag:"🇺🇾", name:"Uruguay",     group:"H", prob:3, peak:3, manager:"Bielsa",     cis:7.9, form:7, chemistry:7.5, change:0,
    strengths:"Bielsa's extreme pressing. Valverde world-class. Núñez and Araújo physical threat. Uruguay consistently over-performs expectations.",
    weaknesses:"High-intensity system risks fatigue in matches 6-8. No obvious creative #10 to unlock deep blocks. Squad depth below top-6 nations.",
    rationale:"Uruguay are the most dangerous team ranked below their probability. Bielsa's system can cause problems on any given day."
  },
  { id:"BEL", flag:"🇧🇪", name:"Belgium",     group:"G", prob:2, peak:2, manager:"Garcia",     cis:6.5, form:7, chemistry:6.8, change:0,
    strengths:"De Bruyne (117 caps, 36 goals) final World Cup. Tielemans at peak. Doku's pace. Lukaku returned and scored his 90th international goal vs Croatia.",
    weaknesses:"Lukaku played only 64 minutes of club football this season — physical readiness for 90-minute knockout matches a concern. Belgium consistently underperform at major tournaments.",
    rationale:"Belgium's individual quality is top-tier but Lukaku's fitness and ageing core reduce realistic ceiling to quarter-finals."
  },
  { id:"JPN", flag:"🇯🇵", name:"Japan",       group:"F", prob:2, peak:2, manager:"Moriyasu",   cis:8.0, form:7, chemistry:7.6, change:0,
    strengths:"Beat England at Wembley in March 2026. Five consecutive wins. Moriyasu's 8-year tenure. Kubo, Kamada, Doan elite-level. Pressing rivals any team.",
    weaknesses:"Lost Mitoma (hamstring), Minamino, and Endo to injury. Late winner vs Iceland showed difficulty breaking compact blocks.",
    rationale:"Japan are the most underrated team in the tournament. Injury losses cap their realistic ceiling at the quarter-finals."
  },
  { id:"MEX", flag:"🇲🇽", name:"Mexico",      group:"A", prob:2, peak:2, manager:"Aguirre",    cis:6.8, form:7, chemistry:7.0, change:0,
    strengths:"Home advantage at Azteca and Akron. Raúl Jiménez and Santi Giménez leading the attack. Settled tactical system. Mexico unbeaten at competitive home matches.",
    weaknesses:"Attacking creativity functional rather than expressive. Vulnerable against high-press systems.",
    rationale:"Mexico's host advantage makes them a genuine R16 threat but ceiling is quarter-finals given attacking quality deficit."
  },
  { id:"CAN", flag:"🇨🇦", name:"Canada",      group:"B", prob:2, peak:2, manager:"Marsch",     cis:7.0, form:7, chemistry:6.9, change:0,
    strengths:"Host-nation energy. Jonathan David, Buchanan, Eustáquio. Marsch's high-pressing system. First World Cup as host since 1986.",
    weaknesses:"Alphonso Davies availability critical unknown. 3 red cards in last 4 matches. Depth drops without Davies.",
    rationale:"Host advantage and pressing system give path to R16 but Davies uncertainty prevents higher probability."
  },
  { id:"USA", flag:"🇺🇸", name:"USA",         group:"D", prob:2, peak:2, manager:"Pochettino",  cis:7.0, form:6, chemistry:6.5, change:0,
    strengths:"Home crowd at SoFi, MetLife. Pulisic broke scoring drought vs Senegal. McKennie at career peak. Pochettino's tactical intelligence.",
    weaknesses:"Pattern of conceding two-goal leads. Defensive transition errors (Robinson giveaways) recurring. Chemistry Score 6.5/10.",
    rationale:"Home advantage gives knockout potential but defensive fragility and limited tournament pedigree keep them as dark horse."
  },
  { id:"KOR", flag:"🇰🇷", name:"South Korea", group:"A", prob:1, peak:1, manager:"Hong",       cis:6.5, form:6, chemistry:6.8, change:0,
    strengths:"Son Heung-min (LAFC) scored brace vs Trinidad. Kim Min-jae (Bayern) anchors defence. High pressing intensity.",
    weaknesses:"Overly Son-dependent. Son at LAFC has less elite-level weekly sharpness than Premier League.",
    rationale:"Path to R16 is realistic but ceiling determined almost entirely by Son's availability and form."
  },
  { id:"COL", flag:"🇨🇴", name:"Colombia",    group:"K", prob:1, peak:1, manager:"Lorenzo",    cis:6.2, form:7, chemistry:7.0, change:0,
    strengths:"Luis Díaz (Bayern Munich) outstanding vs Costa Rica. James Rodríguez experience. Technical midfield quality.",
    weaknesses:"Defensive concentration drops when comfortable. Depth beyond Díaz limited. Lorenzo's CIS lowest of any contender.",
    rationale:"Colombia have talent for a deep run but face Portugal in projected R32 — their ceiling test."
  },
  { id:"TUR", flag:"🇹🇷", name:"Turkey",      group:"D", prob:1, peak:1, manager:"Montella",   cis:6.3, form:6, chemistry:6.5, change:0,
    strengths:"Kenan Yıldız (Juventus, 20) and Arda Güler (Real Madrid, 21) — two of the best young players in the tournament. 4-0 vs North Macedonia showed elite pressing.",
    weaknesses:"No meaningful big-game knockout experience recently. Defensive depth ordinary.",
    rationale:"Tournament's most dangerous second-tier team. Capable of R16 exit but unlikely to go further against elite opposition."
  },
];

export const FACTOR_WEIGHTS = [
  { label:"Recent Team Form",              pct:16, cat:"team",    color:"#2ecc71" },
  { label:"Big-Game Record",               pct:14, cat:"team",    color:"#2ecc71" },
  { label:"Roster Continuity & Chemistry", pct:13, cat:"team",    color:"#2ecc71" },
  { label:"Possession / xG / Tactical",    pct:11, cat:"team",    color:"#2ecc71" },
  { label:"Key Injuries & Squad Depth",    pct:10, cat:"team",    color:"#2ecc71" },
  { label:"Age Balance & Maturity",        pct: 8, cat:"team",    color:"#2ecc71" },
  { label:"Manager Profile (CIS)",         pct:11, cat:"manager", color:"#8bb8f0" },
  { label:"Individual Player Form (IPFI)", pct: 6, cat:"player",  color:"#C9A84C" },
  { label:"Top-5 League Representation",   pct: 2, cat:"context", color:"#8E9BAF" },
  { label:"FIFA Ranking / Elo",            pct: 2, cat:"context", color:"#8E9BAF" },
  { label:"Prestige / Host Advantage",     pct: 2, cat:"context", color:"#8E9BAF" },
  { label:"Pure Luck",                     pct: 5, cat:"luck",    color:"#9b59b6" },
];

const mk=(rank,name,nation,natId,pos,club)=>({
  rank,name,nation,natId,pos,club,
  goals:0,assists:0,apps:0,cleanSheets:0,
  interceptions:0,saves:0,penaltySaves:0,
  yellowCards:0,redCards:0,foulsCommitted:0,foulsDrawn:0,
  rating:0,mins:0
});

export const INITIAL_PLAYERS = [
  mk(1,"Kylian Mbappé","🇫🇷","FRA","FWD","Real Madrid"),
  mk(2,"Lionel Messi","🇦🇷","ARG","MID","Inter Miami"),
  mk(3,"Lamine Yamal","🇪🇸","ESP","FWD","Barcelona"),
  mk(4,"Ousmane Dembélé","🇫🇷","FRA","FWD","PSG"),
  mk(5,"Erling Haaland","🇳🇴","NOR","FWD","Man City"),
  mk(6,"Harry Kane","🏴󠁧󠁢󠁥󠁮󠁧󠁿","ENG","FWD","Bayern Munich"),
  mk(7,"Vinícius Júnior","🇧🇷","BRA","FWD","Real Madrid"),
  mk(8,"Michael Olise","🇫🇷","FRA","MID","Bayern Munich"),
  mk(9,"Pedri","🇪🇸","ESP","MID","Barcelona"),
  mk(10,"Jude Bellingham","🏴󠁧󠁢󠁥󠁮󠁧󠁿","ENG","MID","Real Madrid"),
  mk(11,"Lautaro Martínez","🇦🇷","ARG","FWD","Inter Milan"),
  mk(12,"Désiré Doué","🇫🇷","FRA","FWD","PSG"),
  mk(13,"Rodri","🇪🇸","ESP","MID","Man City"),
  mk(14,"Jamal Musiala","🇩🇪","GER","MID","Bayern Munich"),
  mk(15,"Kevin De Bruyne","🇧🇪","BEL","MID","Man City"),
  mk(16,"Raphinha","🇧🇷","BRA","FWD","Barcelona"),
  mk(17,"Bruno Fernandes","🇵🇹","POR","MID","Man United"),
  mk(18,"Achraf Hakimi","🇲🇦","MAR","DEF","PSG"),
  mk(19,"Federico Valverde","🇺🇾","URU","MID","Real Madrid"),
  mk(20,"Vitinha","🇵🇹","POR","MID","PSG"),
  mk(21,"William Saliba","🇫🇷","FRA","DEF","Arsenal"),
  mk(22,"Thibaut Courtois","🇧🇪","BEL","GK","Real Madrid"),
  mk(23,"Declan Rice","🏴󠁧󠁢󠁥󠁮󠁧󠁿","ENG","MID","Arsenal"),
  mk(24,"Julian Alvarez","🇦🇷","ARG","FWD","Atlético Madrid"),
  mk(25,"Bukayo Saka","🏴󠁧󠁢󠁥󠁮󠁧󠁿","ENG","FWD","Arsenal"),
  mk(26,"Mohamed Salah","🇪🇬","EGY","FWD","Liverpool"),
  mk(27,"Cristiano Ronaldo","🇵🇹","POR","FWD","Al-Nassr"),
  mk(28,"João Neves","🇵🇹","POR","MID","PSG"),
  mk(29,"Sadio Mané","🇸🇳","SEN","FWD","Al-Nassr"),
  mk(30,"Virgil van Dijk","🇳🇱","NED","DEF","Liverpool"),
  mk(31,"Alexis Mac Allister","🇦🇷","ARG","MID","Liverpool"),
  mk(32,"Florian Wirtz","🇩🇪","GER","MID","Bayern Munich"),
  mk(33,"Dani Olmo","🇪🇸","ESP","FWD","Barcelona"),
  mk(34,"Viktor Gyökeres","🇸🇪","SWE","FWD","Arsenal"),
  mk(35,"Arda Güler","🇹🇷","TUR","FWD","Real Madrid"),
  mk(36,"Weston McKennie","🇺🇸","USA","MID","Juventus"),
  mk(37,"Luka Modrić","🇭🇷","CRO","MID","Real Madrid"),
  mk(38,"Christian Pulisic","🇺🇸","USA","FWD","AC Milan"),
  mk(39,"Mike Maignan","🇫🇷","FRA","GK","AC Milan"),
  mk(40,"Son Heung-min","🇰🇷","KOR","FWD","LAFC"),
  mk(41,"Ismaïla Sarr","🇸🇳","SEN","FWD","Crystal Palace"),
  mk(42,"Kenan Yıldız","🇹🇷","TUR","FWD","Juventus"),
  mk(43,"Eberechi Eze","🏴󠁧󠁢󠁥󠁮󠁧󠁿","ENG","MID","Arsenal"),
  mk(44,"Enzo Fernández","🇦🇷","ARG","MID","Chelsea"),
  mk(45,"Cody Gakpo","🇳🇱","NED","FWD","Liverpool"),
  mk(46,"Jonathan David","🇨🇦","CAN","FWD","Lille"),
  mk(47,"Marc Guéhi","🏴󠁧󠁢󠁥󠁮󠁧󠁿","ENG","DEF","Man City"),
  mk(48,"Rafael Leão","🇵🇹","POR","FWD","AC Milan"),
  mk(49,"João Pedro","🇧🇷","BRA","FWD","Chelsea"),
  mk(50,"Jeremie Frimpong","🇳🇱","NED","DEF","Liverpool"),
  mk(51,"Fabián Ruiz","🇪🇸","ESP","MID","PSG"),
  mk(52,"Jules Koundé","🇫🇷","FRA","DEF","Barcelona"),
  mk(53,"Mikel Oyarzabal","🇪🇸","ESP","FWD","Real Sociedad"),
  mk(54,"Gonçalo Ramos","🇵🇹","POR","FWD","PSG"),
  mk(55,"Gianluigi Donnarumma","🇮🇹","ITA","GK","PSG"),
  mk(56,"Mikel Merino","🇪🇸","ESP","MID","Arsenal"),
  mk(57,"Casemiro","🇧🇷","BRA","MID","Man United"),
  mk(58,"Gabriel Martinelli","🇧🇷","BRA","FWD","Arsenal"),
  mk(59,"Reece James","🏴󠁧󠁢󠁥󠁮󠁧󠁿","ENG","DEF","Chelsea"),
  mk(60,"Raúl Jiménez","🇲🇽","MEX","FWD","Fulham"),
  mk(61,"Alexander Isak","🇸🇪","SWE","FWD","Liverpool"),
  mk(62,"Kim Min-jae","🇰🇷","KOR","DEF","Bayern Munich"),
  mk(63,"Bradley Barcola","🇫🇷","FRA","FWD","PSG"),
  mk(64,"Lisandro Martínez","🇦🇷","ARG","DEF","Man United"),
  mk(65,"Marcus Thuram","🇫🇷","FRA","FWD","Inter Milan"),
  mk(66,"Denzel Dumfries","🇳🇱","NED","DEF","Inter Milan"),
  mk(67,"João Cancelo","🇵🇹","POR","DEF","Barcelona"),
  mk(68,"Theo Hernández","🇫🇷","FRA","DEF","AC Milan"),
  mk(69,"Rúben Dias","🇵🇹","POR","DEF","Man City"),
  mk(70,"Rodrigo De Paul","🇦🇷","ARG","MID","Atlético Madrid"),
  mk(71,"Pervis Estupiñán","🇪🇨","ECU","DEF","AC Milan"),
  mk(72,"Joško Gvardiol","🇭🇷","CRO","DEF","Man City"),
  mk(73,"Wout Faes","🇧🇪","BEL","DEF","Leicester"),
  mk(74,"Iñaki Williams","🇬🇭","GHA","FWD","Athletic Bilbao"),
  mk(75,"Jørgen Strand Larsen","🇳🇴","NOR","FWD","Wolves"),
  mk(76,"Antonio Nusa","🇳🇴","NOR","FWD","Club Brugge"),
  mk(77,"Alisson Becker","🇧🇷","BRA","GK","Liverpool"),
  mk(78,"Youri Tielemans","🇧🇪","BEL","MID","Aston Villa"),
  mk(79,"Jeremy Doku","🇧🇪","BEL","FWD","Man City"),
  mk(80,"Romelu Lukaku","🇧🇪","BEL","FWD","Napoli"),
  mk(81,"Takefusa Kubo","🇯🇵","JPN","MID","Real Sociedad"),
  mk(82,"Daichi Kamada","🇯🇵","JPN","MID","Crystal Palace"),
  mk(83,"Bilal Khannouss","🇲🇦","MAR","MID","Genk"),
  mk(84,"Ismail Saibari","🇲🇦","MAR","MID","PSV"),
  mk(85,"Moises Caicedo","🇪🇨","ECU","MID","Chelsea"),
  mk(86,"Luis Díaz","🇨🇴","COL","FWD","Bayern Munich"),
  mk(87,"James Rodríguez","🇨🇴","COL","MID","Rayo Vallecano"),
  mk(88,"Darwin Núñez","🇺🇾","URU","FWD","Liverpool"),
  mk(89,"Rodrigo Bentancur","🇺🇾","URU","MID","Tottenham"),
  mk(90,"Nicolás Jackson","🇸🇳","SEN","FWD","Chelsea"),
  mk(91,"Alphonso Davies","🇨🇦","CAN","DEF","Bayern Munich"),
  mk(92,"Habib Diarra","🇸🇳","SEN","MID","Strasbourg"),
  mk(93,"Takumi Ueda","🇯🇵","JPN","FWD","Feyenoord"),
  mk(94,"Joshua Kimmich","🇩🇪","GER","MID","Bayern Munich"),
  mk(95,"Lennart Karl","🇩🇪","GER","FWD","Bayern Munich"),
  mk(96,"Deniz Undav","🇩🇪","GER","FWD","Stuttgart"),
  mk(97,"Folarin Balogun","🇺🇸","USA","FWD","Monaco"),
  mk(98,"Santi Giménez","🇲🇽","MEX","FWD","AC Milan"),
  mk(99,"Aurélien Tchouaméni","🇫🇷","FRA","MID","Real Madrid"),
  mk(100,"Achraf Dari","🇲🇦","MAR","DEF","Bournemouth"),
];
