const FLAG_URLS = {
  FRA:"https://flagcdn.com/w40/fr.png", ARG:"https://flagcdn.com/w40/ar.png",
  ESP:"https://flagcdn.com/w40/es.png", ENG:"https://flagcdn.com/w40/gb-eng.png",
  BRA:"https://flagcdn.com/w40/br.png", GER:"https://flagcdn.com/w40/de.png",
  POR:"https://flagcdn.com/w40/pt.png", MAR:"https://flagcdn.com/w40/ma.png",
  NED:"https://flagcdn.com/w40/nl.png", URU:"https://flagcdn.com/w40/uy.png",
  BEL:"https://flagcdn.com/w40/be.png", JPN:"https://flagcdn.com/w40/jp.png",
  MEX:"https://flagcdn.com/w40/mx.png", CAN:"https://flagcdn.com/w40/ca.png",
  USA:"https://flagcdn.com/w40/us.png", KOR:"https://flagcdn.com/w40/kr.png",
  COL:"https://flagcdn.com/w40/co.png", TUR:"https://flagcdn.com/w40/tr.png",
  NOR:"https://flagcdn.com/w40/no.png", SEN:"https://flagcdn.com/w40/sn.png",
  CRO:"https://flagcdn.com/w40/hr.png", SWE:"https://flagcdn.com/w40/se.png",
  EGY:"https://flagcdn.com/w40/eg.png", AUT:"https://flagcdn.com/w40/at.png",
  SUI:"https://flagcdn.com/w40/ch.png", GHA:"https://flagcdn.com/w40/gh.png",
  CIV:"https://flagcdn.com/w40/ci.png", SCO:"https://flagcdn.com/w40/gb-sct.png",
  ECU:"https://flagcdn.com/w40/ec.png", PAR:"https://flagcdn.com/w40/py.png",
  AUS:"https://flagcdn.com/w40/au.png", CPV:"https://flagcdn.com/w40/cv.png",
  IRQ:"https://flagcdn.com/w40/iq.png", ALG:"https://flagcdn.com/w40/dz.png",
  JOR:"https://flagcdn.com/w40/jo.png", KSA:"https://flagcdn.com/w40/sa.png",
  IRN:"https://flagcdn.com/w40/ir.png", QAT:"https://flagcdn.com/w40/qa.png",
  CZE:"https://flagcdn.com/w40/cz.png", RSA:"https://flagcdn.com/w40/za.png",
  BIH:"https://flagcdn.com/w40/ba.png", NZL:"https://flagcdn.com/w40/nz.png",
  HAI:"https://flagcdn.com/w40/ht.png", PAN:"https://flagcdn.com/w40/pa.png",
  CUR:"https://flagcdn.com/w40/cw.png", UZB:"https://flagcdn.com/w40/uz.png",
  COD:"https://flagcdn.com/w40/cd.png", TUN:"https://flagcdn.com/w40/tn.png",
};

export function Flag({id, size=24, style={}}){
  const url = FLAG_URLS[id];
  if(!url) return null;
  return <img src={url} alt={id} style={{width:size,height:"auto",borderRadius:2,objectFit:"cover",flexShrink:0,...style}} />;
}

export const FACTOR_WEIGHTS = [
  { label:"Recent Team Form",              pct:16, cat:"team",    color:"#2ecc71" },
  { label:"Big-Game Record",               pct:14, cat:"team",    color:"#2ecc71" },
  { label:"Roster Continuity & Chemistry", pct:13, cat:"team",    color:"#2ecc71" },
  { label:"Possession / xG / Tactical",    pct:11, cat:"team",    color:"#2ecc71" },
  { label:"Key Injuries & Squad Depth",    pct:10, cat:"team",    color:"#2ecc71" },
  { label:"Age Balance & Maturity",        pct: 8, cat:"team",    color:"#2ecc71" },
  { label:"Manager Profile (CIS)",         pct:11, cat:"manager", color:"#8bb8f0" },
  { label:"Individual Player Form (IPFI)", pct: 6, cat:"player",  color:"#C9A84C" },
  { label:"Top-5 League Representation",  pct: 2, cat:"context", color:"#8E9BAF" },
  { label:"FIFA Ranking / Elo",            pct: 2, cat:"context", color:"#8E9BAF" },
  { label:"Prestige / Host Advantage",     pct: 2, cat:"context", color:"#8E9BAF" },
  { label:"Pure Luck",                     pct: 5, cat:"luck",    color:"#9b59b6" },
];

export const MATCH_FACTORS = [
  { label:"Predicted Starting Lineup", pct:null, cat:"match", color:"#f39c12",
    desc:"Starting XI predicted from manager's most-used WC qualification XI and recent friendlies. Confirmed lineups override predictions and trigger probability recalculation." },
  { label:"Key Substitution Impact", pct:null, cat:"match", color:"#e67e22",
    desc:"High-quality bench depth and likely impact subs assessed. Squad rotation due to heat, fixture congestion, and injury risk is factored into match-by-match adjustments." },
  { label:"Team Morale & Recent Form", pct:null, cat:"match", color:"#9b59b6",
    desc:"Carry-over energy from the most recent match result and performance. A convincing win or dispiriting loss creates measurable momentum that influences the next fixture." },
];

// ── FIFA RANKING (approximate 2026, used for tiebreaking) ────────────────────
export const FIFA_RANK = {
  FRA:1,ARG:2,ESP:3,ENG:4,BRA:5,GER:6,POR:7,MAR:8,NED:9,URU:10,
  BEL:11,COL:12,JPN:13,USA:14,MEX:15,KOR:16,TUR:17,NOR:18,SEN:19,
  CRO:10,SUI:21,AUS:22,AUT:26,EGY:44,SWE:25,ECU:47,PAR:62,
  CAN:48,CZE:40,IRN:20,ALG:30,SCO:38,BIH:60,KSA:56,RSA:70,
  QAT:37,NZL:95,IRQ:69,CPV:72,CIV:58,CUR:85,TUN:31,JOR:78,
  COD:76,UZB:80,HAI:88,PAN:73,GHA:65,
};

export const INITIAL_TEAMS = [
  { id:"FRA", flag:"🇫🇷", name:"France",      group:"I", prob:18, peak:18, manager:"Deschamps",    cis:9.1, form:9, chemistry:8.9, change:0,
    strengths:"#1 FIFA ranked. Deepest squad in tournament. Deschamps 14-year tenure. Mbappé, Tchouaméni, Griezmann, Saliba, Theo Hernández all in peak form. Dembélé (Ballon d'Or 2025), Olise, and Doué form explosive wide attacking trio.",
    weaknesses:"Deschamps conservatism can stall against deep blocks. Front-loaded attack can leave midfield transition cover exposed.",
    rationale:"France leads because no team combines system depth, managerial experience, big-game record, and squad chemistry at the same level."
  },
  { id:"ARG", flag:"🇦🇷", name:"Argentina",   group:"J", prob:15, peak:15, manager:"Scaloni",     cis:9.4, form:8, chemistry:9.2, change:0,
    strengths:"Highest Chemistry Score (9.2/10) and Manager CIS (9.4/10). Scaloni's 7+ years. Mac Allister, Enzo Fernández, De Paul most rehearsed midfield trio. Reigning champions.",
    weaknesses:"Messi at 38 physical availability across 8 matches is a concern. Romero and Molina fitness doubts.",
    rationale:"Argentina's team cohesion is unmatched but age-related fatigue risk and key injury doubts prevent them reaching France's probability ceiling."
  },
  { id:"ESP", flag:"🇪🇸", name:"Spain",       group:"H", prob:14, peak:14, manager:"De la Fuente", cis:8.7, form:9, chemistry:8.6, change:0,
    strengths:"Euro 2024 and Nations League winners. Rodri-Pedri axis. Oyarzabal scored in all 6 career finals. Yamal and Dani Olmo explosive.",
    weaknesses:"Yamal fitness race after late-April hamstring injury. Defensive depth behind first-choice CB pairing is thin.",
    rationale:"Spain's form and system are exceptional but Yamal injury uncertainty caps their probability just below Argentina."
  },
  { id:"ENG", flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", name:"England",    group:"L", prob:11, peak:11, manager:"Tuchel",       cis:7.8, form:8, chemistry:7.4, change:0,
    strengths:"Kane, Bellingham, Saka, Eze, Declan Rice, Marc Guéhi, Reece James. Tuchel's CL pedigree resolves structural fragility.",
    weaknesses:"Tuchel only 2 years in. Foden and Palmer not selected. Ben White and Grealish absent.",
    rationale:"England's individual quality and big-game record are elite, but 2 years of system-building leave a creative ceiling gap vs France and Spain."
  },
  { id:"BRA", flag:"🇧🇷", name:"Brazil",      group:"C", prob:9,  peak:9,  manager:"Ancelotti",   cis:7.4, form:7, chemistry:7.1, change:0,
    strengths:"Vinicius Jr in extraordinary form. João Pedro as the #9. Raphinha. Ancelotti's 4x CL pedigree.",
    weaknesses:"Rodrygo (ACL), Militão (hamstring), Estêvão all confirmed out. Largest injury burden of any top-8 side.",
    rationale:"Brazil's ceiling is world-class but their floor has dropped significantly due to the most significant injury crisis of any contender."
  },
  { id:"GER", flag:"🇩🇪", name:"Germany",     group:"E", prob:8,  peak:8,  manager:"Nagelsmann",  cis:7.5, form:8, chemistry:7.3, change:0,
    strengths:"8-match winning streak. Wirtz-Musiala creative axis. Dominant possession metrics.",
    weaknesses:"Gnabry and ter Stegen both out. No major international trophy yet under Nagelsmann.",
    rationale:"Germany's form trajectory and Wirtz-Musiala combination make them a genuine semi-final threat."
  },
  { id:"POR", flag:"🇵🇹", name:"Portugal",    group:"K", prob:7,  peak:7,  manager:"Martínez",    cis:7.6, form:8, chemistry:7.8, change:0,
    strengths:"2025 Nations League winners. Ronaldo, Bruno Fernandes, Bernardo Silva, Vitinha, João Neves, Leão, Gonçalo Ramos.",
    weaknesses:"Ronaldo at 41 creates structural distortions. Knockout-stage fragility historically persistent.",
    rationale:"Portugal's individual quality is top-5 but Ronaldo-dependency and knockout fragility prevent matching France or Spain."
  },
  { id:"MAR", flag:"🇲🇦", name:"Morocco",     group:"C", prob:5,  peak:5,  manager:"Regragui",    cis:8.2, form:8, chemistry:8.4, change:0,
    strengths:"21-match unbeaten streak. Five clean sheets in last six. Hakimi expected fit. Deeply embedded defensive system.",
    weaknesses:"Attacking depth beyond first XI limited.",
    rationale:"Morocco are the tournament's most dangerous defensive unit and most likely team to produce a knockout upset."
  },
  { id:"NED", flag:"🇳🇱", name:"Netherlands", group:"F", prob:4,  peak:4,  manager:"Koeman",      cis:6.8, form:7, chemistry:6.5, change:0,
    strengths:"Van Dijk defensive leadership. Dumfries and Frimpong elite wing-back threat. Gakpo pace and directness.",
    weaknesses:"Xavi Simons (ACL) and Matthijs de Ligt both out. Chemistry Score only 6.5/10.",
    rationale:"Netherlands have the defensive quality to go far but double injury losses reduce them to dangerous outsider."
  },
  { id:"URU", flag:"🇺🇾", name:"Uruguay",     group:"H", prob:3,  peak:3,  manager:"Bielsa",      cis:7.9, form:7, chemistry:7.5, change:0,
    strengths:"Bielsa's extreme pressing. Valverde world-class. Núñez and Araújo physical threat.",
    weaknesses:"High-intensity system risks fatigue in matches 6-8. No obvious creative #10 to unlock deep blocks.",
    rationale:"Uruguay are the most dangerous team ranked below their probability. Bielsa's system can cause problems on any given day."
  },
  { id:"BEL", flag:"🇧🇪", name:"Belgium",     group:"G", prob:2,  peak:2,  manager:"Garcia",      cis:6.5, form:7, chemistry:6.8, change:0,
    strengths:"De Bruyne final World Cup. Tielemans at peak. Doku's pace. Courtois in goal.",
    weaknesses:"Lukaku's physical readiness a concern. Belgium consistently underperform at major tournaments.",
    rationale:"Belgium's individual quality is top-tier but Lukaku's fitness and ageing core reduce ceiling to quarter-finals."
  },
  { id:"JPN", flag:"🇯🇵", name:"Japan",       group:"F", prob:2,  peak:2,  manager:"Moriyasu",    cis:8.0, form:7, chemistry:7.6, change:0,
    strengths:"Beat England at Wembley in March 2026. Moriyasu's 8-year tenure. Kubo, Kamada, Doan elite-level.",
    weaknesses:"Lost Mitoma (hamstring), Minamino, and Endo to injury.",
    rationale:"Japan are the most underrated team in the tournament. Injury losses cap their ceiling at the quarter-finals."
  },
  { id:"MEX", flag:"🇲🇽", name:"Mexico",      group:"A", prob:2,  peak:2,  manager:"Aguirre",     cis:6.8, form:7, chemistry:7.0, change:0,
    strengths:"Home advantage at Azteca and Akron. Raúl Jiménez and Santi Giménez leading the attack.",
    weaknesses:"Attacking creativity functional rather than expressive. Vulnerable against high-press systems.",
    rationale:"Mexico's host advantage makes them a genuine R16 threat but ceiling is quarter-finals."
  },
  { id:"CAN", flag:"🇨🇦", name:"Canada",      group:"B", prob:2,  peak:2,  manager:"Marsch",      cis:7.0, form:7, chemistry:6.9, change:0,
    strengths:"Host-nation energy. Jonathan David, Buchanan, Eustáquio. Marsch's high-pressing system.",
    weaknesses:"Alphonso Davies availability critical unknown. 3 red cards in last 4 matches.",
    rationale:"Host advantage and pressing system give path to R16 but Davies uncertainty prevents higher probability."
  },
  { id:"USA", flag:"🇺🇸", name:"USA",         group:"D", prob:2,  peak:2,  manager:"Pochettino",  cis:7.0, form:6, chemistry:6.5, change:0,
    strengths:"Home crowd at SoFi and MetLife. Pulisic scoring form. McKennie at career peak.",
    weaknesses:"Pattern of conceding two-goal leads. Defensive transition errors recurring.",
    rationale:"Home advantage gives knockout potential but defensive fragility keeps them as dark horse."
  },
  { id:"KOR", flag:"🇰🇷", name:"South Korea", group:"A", prob:1,  peak:1,  manager:"Hong",        cis:6.5, form:6, chemistry:6.8, change:0,
    strengths:"Son Heung-min brace vs Trinidad. Kim Min-jae anchors defence.",
    weaknesses:"Overly Son-dependent.",
    rationale:"Path to R16 realistic but ceiling determined almost entirely by Son's form."
  },
  { id:"COL", flag:"🇨🇴", name:"Colombia",    group:"K", prob:1,  peak:1,  manager:"Lorenzo",     cis:6.2, form:7, chemistry:7.0, change:0,
    strengths:"Luis Díaz (Bayern Munich) outstanding. James Rodríguez experience.",
    weaknesses:"Defensive concentration drops when comfortable. Lorenzo's CIS lowest of any contender.",
    rationale:"Colombia have talent for a deep run but face a tough R32 test."
  },
  { id:"TUR", flag:"🇹🇷", name:"Turkey",      group:"D", prob:1,  peak:1,  manager:"Montella",    cis:6.3, form:6, chemistry:6.5, change:0,
    strengths:"Kenan Yıldız and Arda Güler two of the best young players in the tournament.",
    weaknesses:"No meaningful big-game knockout experience recently.",
    rationale:"Tournament's most dangerous second-tier team. Capable of R16 but unlikely further."
  },
];

export const INITIAL_GROUPS = {
  A:{ name:"A", teams:[{id:"MEX",flag:"🇲🇽",name:"Mexico",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"KOR",flag:"🇰🇷",name:"South Korea",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"CZE",flag:"🇨🇿",name:"Czechia",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"RSA",flag:"🇿🇦",name:"South Africa",w:0,d:0,l:0,gf:0,ga:0,pts:0}]},
  B:{ name:"B", teams:[{id:"CAN",flag:"🇨🇦",name:"Canada",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"SUI",flag:"🇨🇭",name:"Switzerland",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"BIH",flag:"🇧🇦",name:"Bosnia-Herz.",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"QAT",flag:"🇶🇦",name:"Qatar",w:0,d:0,l:0,gf:0,ga:0,pts:0}]},
  C:{ name:"C", teams:[{id:"MAR",flag:"🇲🇦",name:"Morocco",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"BRA",flag:"🇧🇷",name:"Brazil",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"SCO",flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿",name:"Scotland",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"HAI",flag:"🇭🇹",name:"Haiti",w:0,d:0,l:0,gf:0,ga:0,pts:0}]},
  D:{ name:"D", teams:[{id:"USA",flag:"🇺🇸",name:"USA",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"TUR",flag:"🇹🇷",name:"Turkey",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"PAR",flag:"🇵🇾",name:"Paraguay",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"AUS",flag:"🇦🇺",name:"Australia",w:0,d:0,l:0,gf:0,ga:0,pts:0}]},
  E:{ name:"E", teams:[{id:"GER",flag:"🇩🇪",name:"Germany",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"CIV",flag:"🇨🇮",name:"Ivory Coast",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"ECU",flag:"🇪🇨",name:"Ecuador",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"CUR",flag:"🇨🇼",name:"Curaçao",w:0,d:0,l:0,gf:0,ga:0,pts:0}]},
  F:{ name:"F", teams:[{id:"NED",flag:"🇳🇱",name:"Netherlands",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"JPN",flag:"🇯🇵",name:"Japan",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"SWE",flag:"🇸🇪",name:"Sweden",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"TUN",flag:"🇹🇳",name:"Tunisia",w:0,d:0,l:0,gf:0,ga:0,pts:0}]},
  G:{ name:"G", teams:[{id:"BEL",flag:"🇧🇪",name:"Belgium",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"EGY",flag:"🇪🇬",name:"Egypt",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"IRN",flag:"🇮🇷",name:"Iran",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"NZL",flag:"🇳🇿",name:"New Zealand",w:0,d:0,l:0,gf:0,ga:0,pts:0}]},
  H:{ name:"H", teams:[{id:"ESP",flag:"🇪🇸",name:"Spain",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"URU",flag:"🇺🇾",name:"Uruguay",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"KSA",flag:"🇸🇦",name:"Saudi Arabia",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"CPV",flag:"🇨🇻",name:"Cape Verde",w:0,d:0,l:0,gf:0,ga:0,pts:0}]},
  I:{ name:"I", teams:[{id:"FRA",flag:"🇫🇷",name:"France",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"NOR",flag:"🇳🇴",name:"Norway",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"SEN",flag:"🇸🇳",name:"Senegal",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"IRQ",flag:"🇮🇶",name:"Iraq",w:0,d:0,l:0,gf:0,ga:0,pts:0}]},
  J:{ name:"J", teams:[{id:"ARG",flag:"🇦🇷",name:"Argentina",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"AUT",flag:"🇦🇹",name:"Austria",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"ALG",flag:"🇩🇿",name:"Algeria",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"JOR",flag:"🇯🇴",name:"Jordan",w:0,d:0,l:0,gf:0,ga:0,pts:0}]},
  K:{ name:"K", teams:[{id:"POR",flag:"🇵🇹",name:"Portugal",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"COL",flag:"🇨🇴",name:"Colombia",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"COD",flag:"🇨🇩",name:"Congo DR",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"UZB",flag:"🇺🇿",name:"Uzbekistan",w:0,d:0,l:0,gf:0,ga:0,pts:0}]},
  L:{ name:"L", teams:[{id:"ENG",flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿",name:"England",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"CRO",flag:"🇭🇷",name:"Croatia",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"GHA",flag:"🇬🇭",name:"Ghana",w:0,d:0,l:0,gf:0,ga:0,pts:0},{id:"PAN",flag:"🇵🇦",name:"Panama",w:0,d:0,l:0,gf:0,ga:0,pts:0}]},
};

// ── GROUP MATCH PREDICTIONS — score field added to every match ────────────────
// score: [goalsA, goalsB] — predicted scoreline
export const GROUP_MATCH_PREDICTIONS = {
  A:[
    { date:"Jun 12", score:[2,0], a:{id:"MEX",name:"Mexico",prob:65}, b:{id:"KOR",name:"South Korea",prob:20}, draw:15,
      lineup_a:"Ochoa; Sánchez, Montes, Moreno, Gallardo; Herrera, Romo; Antuna, Rodríguez, Vega; Jiménez",
      lineup_b:"Kim Seung-gyu; Kim Moon-hwan, Kim Min-jae, Jung Seung-hyun, Kim Jin-su; Jung Woo-young, Hwang In-beom; Lee Kang-in, Hwang Hee-chan, Na Sang-ho; Son Heung-min",
      key_subs_a:"Giménez provides elite finishing off bench.", key_subs_b:"Cho Gue-sung physical threat from bench.",
      morale_a:"Positive — host nation energy building.", morale_b:"Cautious — Son managed carefully.",
      aS:"Azteca atmosphere, Jiménez leadership, settled system", bS:"Son's match-winning brilliance, Kim Min-jae anchor",
      rat:"Mexico's home advantage and Aguirre's control edge South Korea. Son is the swing factor." },
    { date:"Jun 12", score:[1,1], a:{id:"CZE",name:"Czechia",prob:35}, b:{id:"RSA",name:"South Africa",prob:30}, draw:35,
      lineup_a:"Staněk; Coufal, Čelůstka, Brabec, Boril; Souček, Havel; Lingr, Barák, Hlozek; Schick",
      lineup_b:"Williams; Mudau, Mashele, Sesay, Modiba; Mokoena, Zungu; Tau, Brauteseth, Dolly; Foster",
      key_subs_a:"Provod energy from bench.", key_subs_b:"Lorch pace.",
      morale_a:"Solid — qualified confidently.", morale_b:"High — historic first WC in 32 years.",
      aS:"Schick's elite finishing, Souček aerial dominance", bS:"Historic motivation, Tau's creativity",
      rat:"The most open match of Group A. A draw is the likeliest outcome." },
    { date:"Jun 16", score:[2,1], a:{id:"MEX",name:"Mexico",prob:55}, b:{id:"CZE",name:"Czechia",prob:25}, draw:20,
      lineup_a:"Ochoa; Sánchez, Montes, Moreno, Gallardo; Herrera, Romo; Antuna, Rodríguez, Vega; Jiménez",
      lineup_b:"Staněk; Coufal, Čelůstka, Brabec, Boril; Souček, Havel; Lingr, Barák, Hlozek; Schick",
      key_subs_a:"Giménez and Lozano.", key_subs_b:"Kuchta if chasing.",
      morale_a:"High after opener.", morale_b:"Intact after draw.",
      aS:"Home crowd, Vega creativity, Jiménez dominance", bS:"Schick's clinical finishing",
      rat:"Mexico's home support sees them through. Czechia competitive but outgunned." },
    { date:"Jun 16", score:[2,0], a:{id:"KOR",name:"South Korea",prob:45}, b:{id:"RSA",name:"South Africa",prob:30}, draw:25,
      lineup_a:"Kim Seung-gyu; Kim Moon-hwan, Kim Min-jae, Jung Seung-hyun, Kim Jin-su; Jung Woo-young, Hwang In-beom; Lee Kang-in, Hwang Hee-chan, Na Sang-ho; Son",
      lineup_b:"Williams; Mudau, Mashele, Sesay, Modiba; Mokoena, Zungu; Tau, Brauteseth, Dolly; Foster",
      key_subs_a:"Cho Gue-sung aerial threat.", key_subs_b:"Lorch pace.",
      morale_a:"Motivated response.", morale_b:"Morale depends on opener.",
      aS:"Son's quality gap, Kim Min-jae dominance", bS:"Physical resilience, Tau's flair",
      rat:"Korea win comfortably. Son produces the decisive moments." },
    { date:"Jun 20", score:[3,0], a:{id:"MEX",name:"Mexico",prob:70}, b:{id:"RSA",name:"South Africa",prob:15}, draw:15,
      lineup_a:"Rotation — Giménez leads.", lineup_b:"Full strength — must win.",
      key_subs_a:"Jiménez from bench.", key_subs_b:"Nothing to lose.",
      morale_a:"Qualification secured — confident rotation.", morale_b:"Desperate.",
      aS:"Superior quality even in rotation", bS:"Nothing-to-lose aggression",
      rat:"Mexico comfortably top Group A. Even a rotation XI has too much quality." },
    { date:"Jun 20", score:[1,1], a:{id:"KOR",name:"South Korea",prob:50}, b:{id:"CZE",name:"Czechia",prob:30}, draw:20,
      lineup_a:"Full strength — Son leads.", lineup_b:"Must win.",
      key_subs_a:"Cho Gue-sung.", key_subs_b:"Schick decisive.",
      morale_a:"Final push for second.", morale_b:"Under pressure.",
      aS:"Son's form, pressing intensity", bS:"Schick's experience, Souček power",
      rat:"A tense draw — Korea's draw is enough to secure second on goal difference." },
  ],
  B:[
    { date:"Jun 11", score:[2,0], a:{id:"CAN",name:"Canada",prob:55}, b:{id:"SUI",name:"Switzerland",prob:25}, draw:20,
      lineup_a:"Crepeau; Johnston, Bombito, Miller, Davies; Eustáquio, Kaye; Buchanan, Larin, Osorio; David",
      lineup_b:"Sommer; Widmer, Akanji, Elvedi, Rodriguez; Freuler, Xhaka; Shaqiri, Vargas, Steffen; Seferovic",
      key_subs_a:"Laryea and Millar.", key_subs_b:"Okafor pace.",
      morale_a:"Euphoric — opening home WC match.", morale_b:"Composed underdogs.",
      aS:"Home crowd euphoria, Jonathan David, Davies, Marsch press", bS:"Xhaka composure, Akanji quality",
      rat:"Canada's home energy decisive. David's quality makes the difference." },
    { date:"Jun 11", score:[1,1], a:{id:"BIH",name:"Bosnia-Herz.",prob:40}, b:{id:"QAT",name:"Qatar",prob:30}, draw:30,
      lineup_a:"Šehić; Šunjić, Šatara, Kolašinac; Cimirot, Tahirović, Gazibegović; Gojak, Džeko, Rahimić",
      lineup_b:"Barsham; Ahmed, Hassan, Salman; Ali, Boudiaf; Al-Haydos, Muntari, Ahmed; Al-Moez Ali",
      key_subs_a:"Pjanić creativity.", key_subs_b:"Almoez Ali finishing.",
      morale_a:"Focused — experienced squad.", morale_b:"2022 host experience.",
      aS:"Džeko's quality, European pedigree", bS:"2022 experience, Al-Moez Ali",
      rat:"An open physical match. A draw the likeliest outcome." },
    { date:"Jun 15", score:[2,0], a:{id:"CAN",name:"Canada",prob:50}, b:{id:"BIH",name:"Bosnia-Herz.",prob:30}, draw:20,
      lineup_a:"Crepeau; Johnston, Bombito, Miller, Davies; Eustáquio, Kaye; Buchanan, Larin, Osorio; David",
      lineup_b:"Šehić; Šunjić, Šatara, Kolašinac; Cimirot, Tahirović, Gazibegović; Gojak, Džeko, Rahimić",
      key_subs_a:"Millar, Laryea.", key_subs_b:"Pjanić must start.",
      morale_a:"Confident — targeting qualification.", morale_b:"Under pressure.",
      aS:"Davies and David combination, home advantage", bS:"Džeko experience",
      rat:"Canada's quality too great for Bosnia. David and Davies decisive." },
    { date:"Jun 15", score:[2,1], a:{id:"SUI",name:"Switzerland",prob:45}, b:{id:"QAT",name:"Qatar",prob:30}, draw:25,
      lineup_a:"Sommer; Widmer, Akanji, Elvedi, Rodriguez; Freuler, Xhaka; Shaqiri, Vargas, Steffen; Seferovic",
      lineup_b:"Barsham; Ahmed, Hassan, Salman; Ali, Boudiaf; Al-Haydos, Muntari, Ahmed; Al-Moez Ali",
      key_subs_a:"Okafor pace.", key_subs_b:"All options.",
      morale_a:"Must respond after opener loss.", morale_b:"Desperate for points.",
      aS:"Xhaka leadership, Akanji quality, WC pedigree", bS:"Almoez Ali experience",
      rat:"Switzerland's quality and WC experience sees them through Qatar." },
    { date:"Jun 19", score:[3,1], a:{id:"CAN",name:"Canada",prob:65}, b:{id:"QAT",name:"Qatar",prob:15}, draw:20,
      lineup_a:"Heavy rotation — Millar starts.", lineup_b:"Must win.",
      key_subs_a:"David from bench.", key_subs_b:"Nothing to lose.",
      morale_a:"Already qualified — relaxed.", morale_b:"Elimination pressure.",
      aS:"Depth without standard drop", bS:"Desperate aggression",
      rat:"Even Canada's second-string has too much quality. Comfortable win." },
    { date:"Jun 19", score:[2,1], a:{id:"SUI",name:"Switzerland",prob:50}, b:{id:"BIH",name:"Bosnia-Herz.",prob:30}, draw:20,
      lineup_a:"Full strength.", lineup_b:"Must win.",
      key_subs_a:"Okafor and Zeqiri.", key_subs_b:"Pjanić crucial.",
      morale_a:"Must secure second place.", morale_b:"Final chance.",
      aS:"Switzerland's discipline, Akanji quality", bS:"Džeko's motivation",
      rat:"Switzerland edge Bosnia in a tense decider for second place." },
  ],
  C:[
    { date:"Jun 13", score:[1,0], a:{id:"MAR",name:"Morocco",prob:55}, b:{id:"SCO",name:"Scotland",prob:20}, draw:25,
      lineup_a:"Bounou; Hakimi, Saiss, Dari, Mazraoui; Amrabat, Ounahi; Ziyech, Khannouss, Saibari; En-Nesyri",
      lineup_b:"Gordon; Ralston, McKenna, Hanley, Robertson; McTominay, Gilmour; Christie, McGinn, McLean; Dykes",
      key_subs_a:"Rahimi and El Kaabi.", key_subs_b:"Adams direct option.",
      morale_a:"Strong — 21-match unbeaten run.", morale_b:"Underdog spirit.",
      aS:"21-match unbeaten, Hakimi's threat, Regragui system", bS:"Physical intensity, Robertson set-pieces",
      rat:"Morocco's defensive system built for physical opponents. A composed Moroccan win." },
    { date:"Jun 13", score:[4,0], a:{id:"BRA",name:"Brazil",prob:70}, b:{id:"HAI",name:"Haiti",prob:10}, draw:20,
      lineup_a:"Alisson; Marquinhos; Danilo, Bruno Guimarães, Paquetá, Alex Telles; Raphinha, Vinicius; João Pedro",
      lineup_b:"Josue Duverger; Lherisson, Pierre, Augustin, Luc; Riveros, Thermilus; Herold, Metellus, Nazon; Beauvais",
      key_subs_a:"Neymar when fit. Endrick energy.", key_subs_b:"Historic moment.",
      morale_a:"Cautious optimism — talent still world-class.", morale_b:"Playing with freedom.",
      aS:"Vinicius genius, Raphinha quality, Ancelotti clarity", bS:"Team unity, nothing to lose",
      rat:"Brazil win comfortably from the first whistle. Vinicius and Raphinha dominate." },
    { date:"Jun 17", score:[1,1], a:{id:"MAR",name:"Morocco",prob:60}, b:{id:"BRA",name:"Brazil",prob:25}, draw:15,
      lineup_a:"Bounou; Hakimi, Saiss, Dari, Mazraoui; Amrabat, Ounahi; Ziyech, Khannouss, Saibari; En-Nesyri",
      lineup_b:"Alisson; Marquinhos; Danilo, Bruno Guimarães, Paquetá, Alex Telles; Raphinha, Vinicius; João Pedro",
      key_subs_a:"Defensive options — Regragui frustrates.", key_subs_b:"Neymar from bench.",
      morale_a:"Flying — confident, can replicate 2022 magic.", morale_b:"Under scrutiny.",
      aS:"Defensive mastery, Amrabat neutralising Paquetá", bS:"Vinicius and Raphinha's individual quality",
      rat:"The group stage match of the tournament. Morocco nicks it on a counter — predicted 1-1 draw." },
    { date:"Jun 17", score:[2,0], a:{id:"SCO",name:"Scotland",prob:55}, b:{id:"HAI",name:"Haiti",prob:20}, draw:25,
      lineup_a:"Gordon; Ralston, McKenna, Hanley, Robertson; McTominay, Gilmour; Christie, McGinn, McLean; Dykes",
      lineup_b:"Duverger; Lherisson, Pierre, Augustin, Luc; Riveros, Thermilus; Herold, Metellus, Nazon; Beauvais",
      key_subs_a:"Adams and Shankland.", key_subs_b:"Full strength.",
      morale_a:"Must bounce back.", morale_b:"Inspired by their appearance.",
      aS:"McTominay quality, Robertson delivery, Scottish physicality", bS:"Spirited underdog energy",
      rat:"Scotland must win this to stay in. Quality shows against Haiti." },
    { date:"Jun 21", score:[3,0], a:{id:"MAR",name:"Morocco",prob:75}, b:{id:"HAI",name:"Haiti",prob:10}, draw:15,
      lineup_a:"Significant rotation.", lineup_b:"Full strength — final chance.",
      key_subs_a:"Fresh players.", key_subs_b:"Everything.",
      morale_a:"Already qualified — professional.", morale_b:"Pride.",
      aS:"Morocco depth still superior", bS:"Desperation",
      rat:"Morocco coast through. Regragui rests key players for knockouts." },
    { date:"Jun 21", score:[3,1], a:{id:"BRA",name:"Brazil",prob:65}, b:{id:"SCO",name:"Scotland",prob:20}, draw:15,
      lineup_a:"Full strength — must assert quality.", lineup_b:"Must win.",
      key_subs_a:"Neymar if fit. Endrick fresh.", key_subs_b:"Adams leads.",
      morale_a:"Determined — pride demands a win.", morale_b:"All or nothing.",
      aS:"Brazil's class when fully focused, Vinicius and Raphinha", bS:"McTominay, Robertson heart",
      rat:"Brazil respond after the Morocco draw. Quality tells over 90 minutes." },
  ],
  D:[
    { date:"Jun 12", score:[2,1], a:{id:"USA",name:"USA",prob:55}, b:{id:"TUR",name:"Turkey",prob:25}, draw:20,
      lineup_a:"Turner; Dest, Richards, Ream, Robinson; Adams, McKennie; Reyna, Musah, Pulisic; Balogun",
      lineup_b:"Çakır; Müldür, Demiral, Kadıoğlu; Tokoz, Calhanoglu; Güler, Yıldız; Aktürkoğlu",
      key_subs_a:"Weah and Ferreira.", key_subs_b:"Yazıcı creativity.",
      morale_a:"Home crowd at SoFi — massive occasion.", morale_b:"Yıldız and Güler excited.",
      aS:"Home crowd, McKennie peak, Pulisic form", bS:"Yıldız-Güler duo, dangerous counter",
      rat:"USA's home advantage and Pulisic form edge Turkey. Güler's quality makes it dangerous." },
    { date:"Jun 12", score:[1,1], a:{id:"PAR",name:"Paraguay",prob:40}, b:{id:"AUS",name:"Australia",prob:35}, draw:25,
      lineup_a:"Arias; Alderete, Balbuena, Alonso; Espinoza, Rojas; Sanabria, Enciso, Almirón; Valdez",
      lineup_b:"Ryan; Degenek, Rowles, Souttar, Behich; Irvine, Mooy; Leckie, Hrustic, Baccus; Maclaren",
      key_subs_a:"Derlis González.", key_subs_b:"Duke physicality.",
      morale_a:"South American confidence.", morale_b:"Mooy's final WC.",
      aS:"Almirón's quality, South American mentality", bS:"Mooy's control, Ryan shot-stopping",
      rat:"Genuinely open. A draw is the likeliest outcome." },
    { date:"Jun 16", score:[3,0], a:{id:"USA",name:"USA",prob:60}, b:{id:"PAR",name:"Paraguay",prob:20}, draw:20,
      lineup_a:"Full strength.", lineup_b:"Must win or need miracle.",
      key_subs_a:"Reyna creativity.", key_subs_b:"All attacking options.",
      morale_a:"Confident — crowd building.", morale_b:"Under immense pressure.",
      aS:"Home crowd, McKennie, Pulisic leadership", bS:"Almirón quality in tight games",
      rat:"USA's home advantage and quality see them through Paraguay comfortably." },
    { date:"Jun 16", score:[2,1], a:{id:"TUR",name:"Turkey",prob:45}, b:{id:"AUS",name:"Australia",prob:30}, draw:25,
      lineup_a:"Same XI — Yıldız-Güler combination.", lineup_b:"Compact defence first.",
      key_subs_a:"Yazıcı from bench.", key_subs_b:"Mabil and Duke.",
      morale_a:"Must bounce back — quality too high to exit.", morale_b:"Belief from opener.",
      aS:"Yıldız and Güler potential, pressing intensity", bS:"Mooy experience, Ryan goalkeeping",
      rat:"Turkey's individual quality edges Australia. Güler's dead ball quality decisive." },
    { date:"Jun 20", score:[3,0], a:{id:"USA",name:"USA",prob:65}, b:{id:"AUS",name:"Australia",prob:20}, draw:15,
      lineup_a:"Possible rotation.", lineup_b:"Final chance — must-win.",
      key_subs_a:"Weah fresh. Balogun bench.", key_subs_b:"Full intensity.",
      morale_a:"Likely qualified — managing load.", morale_b:"All or nothing.",
      aS:"Home crowd, qualified momentum, Pulisic class", bS:"Must-win intensity, Mooy leadership",
      rat:"USA's quality too great even with rotation." },
    { date:"Jun 20", score:[2,0], a:{id:"TUR",name:"Turkey",prob:50}, b:{id:"PAR",name:"Paraguay",prob:30}, draw:20,
      lineup_a:"Full strength — must win to qualify.", lineup_b:"Must win — tournament life.",
      key_subs_a:"All attacking.", key_subs_b:"Almirón must deliver.",
      morale_a:"Excited — Yıldız and Güler in biggest game.", morale_b:"Desperate — defend deep.",
      aS:"Yıldız-Güler too good for Paraguay", bS:"South American resilience",
      rat:"Turkey's attacking quality sees them through. Yıldız's individual moments decide it." },
  ],
  E:[
    { date:"Jun 13", score:[3,0], a:{id:"GER",name:"Germany",prob:75}, b:{id:"CIV",name:"Ivory Coast",prob:10}, draw:15,
      lineup_a:"Trapp; Kimmich, Rüdiger, Tah, Raum; Andrich, Kroos; Musiala, Wirtz, Sané; Havertz",
      lineup_b:"Sangaré; Aurier, Badié, Boly, Koné; Seri; Pépé, Zaha, Traoré; Haller",
      key_subs_a:"Karl pace.", key_subs_b:"Gradel experience.",
      morale_a:"Flying — 8-match winning streak.", morale_b:"Motivated but realistic.",
      aS:"8-match streak, Wirtz-Musiala dominance", bS:"Haller physicality, AFCON block",
      rat:"Germany's pressing dismantles Ivory Coast. A comfortable win." },
    { date:"Jun 13", score:[2,0], a:{id:"ECU",name:"Ecuador",prob:45}, b:{id:"CUR",name:"Curaçao",prob:25}, draw:30,
      lineup_a:"Domínguez; Preciado, Hincapié, Torres, Estupiñán; Caicedo, Gruezo; Plata, Sarmiento, Méndez; Valencia",
      lineup_b:"Marsman; Cijntje, Aias, Dos Santos, Fleming; Bacuna, Fer; Martina, Boymans, Clasie; Sarmiento",
      key_subs_a:"Enner Valencia.", key_subs_b:"Limited depth.",
      morale_a:"South American confidence, Caicedo quality.", morale_b:"Historic debut.",
      aS:"Caicedo elite quality, Estupiñán, SA experience", bS:"Nothing to lose, Bacuna and Fer",
      rat:"Ecuador's quality too great. Caicedo dominates." },
    { date:"Jun 17", score:[2,0], a:{id:"GER",name:"Germany",prob:70}, b:{id:"ECU",name:"Ecuador",prob:15}, draw:15,
      lineup_a:"Full strength.", lineup_b:"Must defend compactly.",
      key_subs_a:"Karl and Adeyemi.", key_subs_b:"Valencia impact.",
      morale_a:"Unstoppable momentum.", morale_b:"Determined to upset.",
      aS:"Germany's complete system, Wirtz at peak", bS:"Caicedo's quality, Estupiñán disruption",
      rat:"Germany's quality too great. Ecuador defends well but is overwhelmed." },
    { date:"Jun 17", score:[2,1], a:{id:"CIV",name:"Ivory Coast",prob:55}, b:{id:"CUR",name:"Curaçao",prob:20}, draw:25,
      lineup_a:"Full strength — must get points.", lineup_b:"Nothing to lose.",
      key_subs_a:"Gradel and Diabaté.", key_subs_b:"All options.",
      morale_a:"Must-win mentality.", morale_b:"Enjoying the ride.",
      aS:"AFCON quality, Haller physicality, Zaha", bS:"Bacuna and Fer's quality, energy",
      rat:"Ivory Coast's experience overcomes Curaçao to keep last-16 hopes alive." },
    { date:"Jun 21", score:[4,0], a:{id:"GER",name:"Germany",prob:70}, b:{id:"CUR",name:"Curaçao",prob:10}, draw:20,
      lineup_a:"Heavy rotation.", lineup_b:"Full strength.",
      key_subs_a:"Karl and Adeyemi lead.", key_subs_b:"Historic opportunity.",
      morale_a:"Already qualified — managing fitness.", morale_b:"Inspired by experience.",
      aS:"Germany's depth maintains quality", bS:"Tournament experience, Bacuna quality",
      rat:"Germany's depth is extraordinary. Large comfortable win even in rotation." },
    { date:"Jun 21", score:[2,1], a:{id:"ECU",name:"Ecuador",prob:55}, b:{id:"CIV",name:"Ivory Coast",prob:25}, draw:20,
      lineup_a:"Full strength — second place on the line.", lineup_b:"Must win to advance.",
      key_subs_a:"Valencia decisive moments.", key_subs_b:"Haller and Pépé.",
      morale_a:"Confident — Caicedo motivated.", morale_b:"All-or-nothing.",
      aS:"Caicedo's quality, Estupiñán dominance, WC experience", bS:"Haller experience, AFCON quality",
      rat:"Ecuador edge Ivory Coast. Caicedo's quality in big matches is decisive." },
  ],
  F:[
    { date:"Jun 14", score:[1,1], a:{id:"NED",name:"Netherlands",prob:55}, b:{id:"JPN",name:"Japan",prob:25}, draw:20,
      lineup_a:"Flekken; Dumfries, Van Dijk, De Vrij, Frimpong; De Jong, Taylor; Reijnders, Gakpo, Malen; Weghorst",
      lineup_b:"Gonda; Tomiyasu, Taniguchi, Itakura, Udokawa; Ito, Kamada; Kubo, Nakamura, Doan; Ueda",
      key_subs_a:"Zirkzee off bench.", key_subs_b:"Furuhashi pace.",
      morale_a:"Cautious — injuries hurt confidence.", morale_b:"Buzzing — beat England at Wembley.",
      aS:"Van Dijk leadership, Frimpong Liverpool form, wing-back dominance", bS:"Beat England at Wembley, Kubo and Kamada, world-class pressing",
      rat:"Japan's pressing targets the creative void left by Simons. A tense draw — Netherlands nick a point." },
    { date:"Jun 14", score:[2,0], a:{id:"SWE",name:"Sweden",prob:45}, b:{id:"TUN",name:"Tunisia",prob:30}, draw:25,
      lineup_a:"Olsen; Krafth, Lindelöf, Danielson, Augustinsson; Svanberg, Olsson; Forsberg, Claesson, Kulusevski; Isak",
      lineup_b:"Dahmen; Drager, Maaloul, Ben Naceur, Bronn; Ben Amor, Skhiri; Khazri, Badri; Khazri",
      key_subs_a:"Gyökeres lethal from bench.", key_subs_b:"Sliti creativity.",
      morale_a:"Isak-Gyökeres combination generating excitement.", morale_b:"Experienced, composed.",
      aS:"Isak Liverpool form, Gyökeres Arsenal brilliance, Kulusevski quality", bS:"Tunisia's defensive organisation, Khazri experience",
      rat:"Sweden's attacking quality too great for Tunisia. A comfortable Swedish win." },
    { date:"Jun 18", score:[2,1], a:{id:"NED",name:"Netherlands",prob:60}, b:{id:"SWE",name:"Sweden",prob:25}, draw:15,
      lineup_a:"Full strength.", lineup_b:"Confident after Tunisia win.",
      key_subs_a:"Zirkzee off bench.", key_subs_b:"Gyökeres leads if rested.",
      morale_a:"Under pressure — must respond.", morale_b:"Riding high.",
      aS:"Van Dijk authority, wing-back dominance, Gakpo class", bS:"Gyökeres and Isak elite, Kulusevski quality",
      rat:"Netherlands individual quality sees them through Sweden. Gyökeres is the danger." },
    { date:"Jun 18", score:[2,0], a:{id:"JPN",name:"Japan",prob:60}, b:{id:"TUN",name:"Tunisia",prob:20}, draw:20,
      lineup_a:"Full strength.", lineup_b:"Must win.",
      key_subs_a:"Furuhashi. Maeda.", key_subs_b:"Sliti and Jaziri.",
      morale_a:"Confidence sky-high.", morale_b:"Under pressure.",
      aS:"Japan's pressing, Kubo and Kamada creativity", bS:"Tunisia defensive discipline, Khazri experience",
      rat:"Japan's pressing overwhelms Tunisia's block. Kubo's quality decisive." },
    { date:"Jun 22", score:[3,0], a:{id:"NED",name:"Netherlands",prob:65}, b:{id:"TUN",name:"Tunisia",prob:15}, draw:20,
      lineup_a:"Rotation possible.", lineup_b:"Final game.",
      key_subs_a:"Zirkzee and Bergwijn.", key_subs_b:"All options.",
      morale_a:"Qualification secured — managing load.", morale_b:"Tournament end.",
      aS:"Dutch quality overwhelming even in rotation", bS:"Organised block",
      rat:"Netherlands comfortably win even in partial rotation." },
    { date:"Jun 22", score:[2,1], a:{id:"JPN",name:"Japan",prob:55}, b:{id:"SWE",name:"Sweden",prob:30}, draw:15,
      lineup_a:"Full strength — targeting group victory.", lineup_b:"Must win for second.",
      key_subs_a:"Pressing maintained.", key_subs_b:"Gyökeres leads.",
      morale_a:"Historic achievement in sight.", morale_b:"Gyökeres motivated.",
      aS:"Japan's pressing more sophisticated, Kubo quality, collective intensity", bS:"Isak and Gyökeres elite combination, Kulusevski",
      rat:"Japan's collective system edges Sweden's individual brilliance in a tense contest." },
  ],
  G:[
    { date:"Jun 14", score:[2,1], a:{id:"BEL",name:"Belgium",prob:60}, b:{id:"EGY",name:"Egypt",prob:20}, draw:20,
      lineup_a:"Courtois; Castagne, Faes, Theate, Carrasco; De Bruyne, Tielemans; Doku, De Ketelaere, Mertens; Lukaku",
      lineup_b:"El-Shenawy; Ashraf, Hamdy, Abdelmonem, Magdi; Elneny, Zizo; Salah, Trezeguet, Emam Ashour; El-Kaabı",
      key_subs_a:"Batshuayi physicality.", key_subs_b:"Mostafa Mohamed.",
      morale_a:"De Bruyne's final WC — peak motivation.", morale_b:"Salah's final shot at glory.",
      aS:"De Bruyne genius, Courtois world-class, Doku pace", bS:"Salah's 54 goals, defensive organisation",
      rat:"The emotional match of Group G. De Bruyne vs Salah. Belgium's depth edges it." },
    { date:"Jun 14", score:[2,0], a:{id:"IRN",name:"Iran",prob:40}, b:{id:"NZL",name:"New Zealand",prob:30}, draw:30,
      lineup_a:"Beiranvand; Rezaeian, Hosseini, Pouraliganji, Hajsafi; Ezatolahi, Noorollahi; Jahanbakhsh, Taremi, Ghoddos; Azmoun",
      lineup_b:"Marinovic; Long, Woud, Wood, Lewis; McGlinchey, Gould; Cacace, Bodart, Sutton; Payne",
      key_subs_a:"Gholizadeh pace.", key_subs_b:"Payne target.",
      morale_a:"Taremi Inter Milan form — sharp.", morale_b:"Historic second WC.",
      aS:"Taremi elite finishing, Azmoun experience", bS:"New Zealand spirit, Cacace Serie A quality",
      rat:"Iran have too much quality. Taremi's finishing decides it." },
    { date:"Jun 18", score:[3,0], a:{id:"BEL",name:"Belgium",prob:65}, b:{id:"IRN",name:"Iran",prob:20}, draw:15,
      lineup_a:"Full strength.", lineup_b:"Compact block — Taremi on counter.",
      key_subs_a:"De Ketelaere fresh.", key_subs_b:"Gholizadeh pace.",
      morale_a:"Building momentum.", morale_b:"Motivated after opener.",
      aS:"De Bruyne vision, Doku pace, Lukaku presence", bS:"Taremi clinical on counter",
      rat:"Belgium's quality too great for Iran. De Bruyne and Doku create too many chances." },
    { date:"Jun 18", score:[2,1], a:{id:"EGY",name:"Egypt",prob:50}, b:{id:"NZL",name:"New Zealand",prob:25}, draw:25,
      lineup_a:"Full strength — Salah leads.", lineup_b:"Resilient block.",
      key_subs_a:"Mostafa Mohamed.", key_subs_b:"Payne impact.",
      morale_a:"Salah's final WC — desperate to advance.", morale_b:"Playing for pride.",
      aS:"Salah's individual brilliance, AFCON experience", bS:"New Zealand resilience, Cacace quality",
      rat:"Salah's quality decisive against New Zealand's organised defence." },
    { date:"Jun 22", score:[4,0], a:{id:"BEL",name:"Belgium",prob:65}, b:{id:"NZL",name:"New Zealand",prob:15}, draw:20,
      lineup_a:"Rotation.", lineup_b:"Final game.",
      key_subs_a:"Origi and Batshuayi.", key_subs_b:"Full options.",
      morale_a:"Already qualified.", morale_b:"Play for pride.",
      aS:"Belgian depth superior even rotating", bS:"Underdog spirit",
      rat:"Belgium comfortably win even rotating heavily." },
    { date:"Jun 22", score:[2,1], a:{id:"EGY",name:"Egypt",prob:55}, b:{id:"IRN",name:"Iran",prob:25}, draw:20,
      lineup_a:"Must win — Salah leads.", lineup_b:"Must win — Taremi leads.",
      key_subs_a:"Mostafa Mohamed.", key_subs_b:"Gholizadeh pace.",
      morale_a:"Everything to play for — Salah's legacy.", morale_b:"Taremi Inter quality must show.",
      aS:"Salah's 54 goals, AFCON quality, experience", bS:"Taremi clinical, defensive organisation",
      rat:"The Salah-Taremi showdown. Egypt's greater depth and Salah's motivation edge it." },
  ],
  H:[
    { date:"Jun 15", score:[4,0], a:{id:"ESP",name:"Spain",prob:80}, b:{id:"KSA",name:"Saudi Arabia",prob:8}, draw:12,
      lineup_a:"Unai Simón; Carvajal, Nacho, Le Normand, Cucurella; Rodri, Pedri; Yamal, Olmo, Williams N.; Oyarzabal",
      lineup_b:"Al-Owais; Al-Burayk, Al-Amri, Al-Bulaihi, Al-Shahrani; Al-Dawsari, Al-Malki; Al-Shehri, Saleh, Bahebri; Al-Nemer",
      key_subs_a:"Morata. Torres. Merino.", key_subs_b:"Kanno creativity.",
      morale_a:"Euro 2024 and Nations League champions — supreme confidence.", morale_b:"Motivated by 2022 Argentina shock.",
      aS:"Euro 2024 and NL winners, Rodri-Pedri dominance, Yamal-Olmo creativity", bS:"2022 Argentina shock, Al-Dawsari quality, deep block",
      rat:"Spain's possession system perfectly dismantles compact teams. A comfortable Spanish win." },
    { date:"Jun 15", score:[3,0], a:{id:"URU",name:"Uruguay",prob:60}, b:{id:"CPV",name:"Cape Verde",prob:20}, draw:20,
      lineup_a:"Rochet; Nández, Araújo, Godín, Olivera; Bentancur, Ugarte; Valverde, De la Cruz, Pellistri; Núñez",
      lineup_b:"Vozinha; Garry Rodrigues, Roberto, Tavares, Semedo; William Tavares, Lopes; Andrade, Carlinhos, Jamiro; Jovane",
      key_subs_a:"Cavani if available.", key_subs_b:"Djaniny target.",
      morale_a:"Valverde at peak — Bielsa humming.", morale_b:"Playing with freedom.",
      aS:"Valverde brilliance, Bielsa press, Núñez physicality", bS:"AFCON surprise qualifiers, Jovane Sporting quality",
      rat:"Uruguay's pressing overwhelms Cape Verde. Valverde and Núñez dominate." },
    { date:"Jun 19", score:[2,0], a:{id:"ESP",name:"Spain",prob:75}, b:{id:"URU",name:"Uruguay",prob:15}, draw:10,
      lineup_a:"Full strength — asserting dominance.", lineup_b:"Bielsa pressing at maximum.",
      key_subs_a:"Morata physicality. Torres.", key_subs_b:"De la Cruz. Pellistri.",
      morale_a:"Dominant — building form.", morale_b:"Massive challenge — Bielsa's defining test.",
      aS:"Rodri and Pedri possession control, defensive organisation, Yamal creativity", bS:"Bielsa's press — can disrupt any system. Valverde and Núñez elite.",
      rat:"Spain's possession vs Bielsa's press. Spain's technical quality and Rodri's game management prevails." },
    { date:"Jun 19", score:[2,1], a:{id:"KSA",name:"Saudi Arabia",prob:50}, b:{id:"CPV",name:"Cape Verde",prob:25}, draw:25,
      lineup_a:"Full strength — must win.", lineup_b:"Playing for pride and upset.",
      key_subs_a:"All options.", key_subs_b:"Djaniny target.",
      morale_a:"Under pressure — last chance.", morale_b:"Inspired by experience.",
      aS:"AFC quality, Al-Dawsari experience, regional support", bS:"Cape Verde AFCON quality, spirit",
      rat:"Saudi Arabia's greater experience sees them through Cape Verde." },
    { date:"Jun 23", score:[3,0], a:{id:"ESP",name:"Spain",prob:70}, b:{id:"CPV",name:"Cape Verde",prob:10}, draw:20,
      lineup_a:"Heavy rotation — Rodri and Pedri rested.", lineup_b:"Full strength — historic upset chance.",
      key_subs_a:"Merino and Fabián lead. Torres starts.", key_subs_b:"All options.",
      morale_a:"Already qualified — Yamal and Rodri rested.", morale_b:"Once-in-a-lifetime opportunity.",
      aS:"Spain's depth maintains quality even rotating 6-7 players", bS:"Nothing to lose — could upset",
      rat:"Spain rotate heavily but still have too much quality." },
    { date:"Jun 23", score:[2,0], a:{id:"URU",name:"Uruguay",prob:65}, b:{id:"KSA",name:"Saudi Arabia",prob:20}, draw:15,
      lineup_a:"Full strength — must secure second.", lineup_b:"Must win — elimination pressure.",
      key_subs_a:"Cavani and Suárez farewell.", key_subs_b:"Al-Dawsari must deliver.",
      morale_a:"Valverde — second place the mission.", morale_b:"Desperate.",
      aS:"Valverde world-class, Bielsa pressing, Núñez physicality", bS:"Al-Dawsari experience, defensive organisation",
      rat:"Uruguay's quality far superior. Valverde's brilliance sees them comfortably to second." },
  ],
  I:[
    { date:"Jun 11", score:[4,0], a:{id:"FRA",name:"France",prob:80}, b:{id:"IRQ",name:"Iraq",prob:8}, draw:12,
      lineup_a:"Maignan; Kounde, Saliba, Upamecano, T.Hernández; Tchouaméni, Griezmann; Dembélé, Olise, Doué; Mbappé",
      lineup_b:"Bashar Rashid; Ali Adnan, Husam, Abbas, Mashal; Mohannad, Karrar; Qassim, Ameen, Younus; Moatasum",
      key_subs_a:"Thuram. Camavinga. Barcola.", key_subs_b:"Iraq play for pride.",
      morale_a:"Pre-tournament favourites — composed and ready.", morale_b:"First appearance since 1986.",
      aS:"#1 FIFA rank, Mbappé-Dembélé-Olise-Doué, Saliba-Upamecano axis", bS:"Nothing to lose, Iraqi pride",
      rat:"France's most comfortable group game. A showcase for France's extraordinary attacking depth." },
    { date:"Jun 11", score:[2,1], a:{id:"NOR",name:"Norway",prob:55}, b:{id:"SEN",name:"Senegal",prob:25}, draw:20,
      lineup_a:"Nyland; Pedersen, Østigård, Hanche-Olsen, Meling; Nørgaard, Thorsby; Ødegaard, Sørloth, Nusa; Haaland",
      lineup_b:"Mendy; Sabaly, Koulibaly, Cissé, Jakobs; Kouyaté, Diatta; Sarr, Mané, Diallo; Jackson",
      key_subs_a:"Strand Larsen from bench.", key_subs_b:"Habib Diarra. Boulaye Dia.",
      morale_a:"Haaland's first WC — massive motivation.", morale_b:"Mané's final chance — 54 goals.",
      aS:"Haaland 55 goals — most prolific striker at tournament, Ødegaard creativity", bS:"Mané 54 goals, Koulibaly experience, Sarr and Jackson",
      rat:"Haaland vs Mané. Norway's squad depth edges Senegal." },
    { date:"Jun 15", score:[3,0], a:{id:"FRA",name:"France",prob:75}, b:{id:"SEN",name:"Senegal",prob:15}, draw:10,
      lineup_a:"Full strength — maintaining dominance.", lineup_b:"Mané-led — desperate for points.",
      key_subs_a:"Thuram and Barcola.", key_subs_b:"Diarra, Dia.",
      morale_a:"Flying after Iraq — Dembélé establishing himself.", morale_b:"Under pressure.",
      aS:"Saliba-Upamecano impenetrable against Mané, Mbappé counter decisive", bS:"Mané's individual quality can conjure goals against any defence",
      rat:"Saliba and Upamecano neutralise Mané's physical threat. France's depth decisive." },
    { date:"Jun 15", score:[3,0], a:{id:"NOR",name:"Norway",prob:65}, b:{id:"IRQ",name:"Iraq",prob:15}, draw:20,
      lineup_a:"Full strength — group victory target.", lineup_b:"Every moment counts.",
      key_subs_a:"Strand Larsen.", key_subs_b:"Iraq youth.",
      morale_a:"Haaland on the scoresheet — momentum.", morale_b:"Inspired by France performance.",
      aS:"Haaland's finishing, Ødegaard's vision, Norway's direct style", bS:"Iraqi pride, historic participation",
      rat:"Haaland's quality against Iraq produces goals. Norway comfortably win." },
    { date:"Jun 19", score:[2,0], a:{id:"FRA",name:"France",prob:75}, b:{id:"NOR",name:"Norway",prob:15}, draw:10,
      lineup_a:"Full strength — setting knockout tone.", lineup_b:"Haaland's defining moment.",
      key_subs_a:"Rest Mbappé for 70 — Barcola and Doué.", key_subs_b:"Strand Larsen from bench.",
      morale_a:"Already qualified — managing for knockouts.", morale_b:"Biggest match in Norwegian history.",
      aS:"Saliba-Upamecano axis built for Haaland, Mbappé counter decisive", bS:"Haaland — one-man army. Ødegaard and Nusa support.",
      rat:"Haaland is the greatest threat France face in the group. But Saliba's dominance and Mbappé's counter decisive." },
    { date:"Jun 19", score:[2,0], a:{id:"SEN",name:"Senegal",prob:65}, b:{id:"IRQ",name:"Iraq",prob:20}, draw:15,
      lineup_a:"Full strength — must win.", lineup_b:"Playing for pride.",
      key_subs_a:"Dia and Diedhiou.", key_subs_b:"Iraq youth.",
      morale_a:"Mané desperate — final WC moment.", morale_b:"National pride.",
      aS:"Mané 54 goals, Koulibaly experience, Sarr and Jackson", bS:"Iraqi spirit",
      rat:"Mané's motivation in his likely final WC game produces a strong Senegal performance." },
  ],
  J:[
    { date:"Jun 12", score:[4,0], a:{id:"ARG",name:"Argentina",prob:80}, b:{id:"ALG",name:"Algeria",prob:8}, draw:12,
      lineup_a:"E.Martínez; Montiel, Romero, Otamendi, Acuña; Mac Allister, Enzo; De Paul, Lautaro; Messi",
      lineup_b:"Benali; Mandouki, Mandi, Benlamri, Ait Nouri; Guendouzi, Zerrouki; Mahrez, Belaili, Aouar; Slimani",
      key_subs_a:"J.Álvarez from bench.", key_subs_b:"Mahrez from bench. Bounedjah.",
      morale_a:"Defending champions — immense confidence.", morale_b:"AFCON qualifiers — quality gap enormous.",
      aS:"9.2/10 chemistry, Scaloni system, Mac Allister-Enzo-De Paul, Messi genius", bS:"Guendouzi and Mahrez quality, Ait Nouri",
      rat:"Argentina's chemistry and system too great for Algeria. Messi's genius controls the game." },
    { date:"Jun 12", score:[3,0], a:{id:"AUT",name:"Austria",prob:50}, b:{id:"JOR",name:"Jordan",prob:25}, draw:25,
      lineup_a:"Pentz; Trimmel, Trauner, Posch, Mwene; Laimer, Schlager; Sabitzer, Grüll, Baumgartner; Arnautović",
      lineup_b:"Shnaishel; Musa, Nawas, Al-Rawabdeh, Dawood; Hassan, Nasib; Baha', Khaled, Sobieh; Al-Tawahaa",
      key_subs_a:"Kainz creativity. Gregoritsch target.", key_subs_b:"Limited depth.",
      morale_a:"Rangnick's Red Bull press — Austria punching above weight.", morale_b:"Historic occasion — first WC.",
      aS:"Rangnick's famous press, Arnautović experience, Laimer CL quality", bS:"Jordan's historic debut, disciplined block",
      rat:"Austria's pressing machine too strong for Jordan. Quality gap too large." },
    { date:"Jun 16", score:[3,1], a:{id:"ARG",name:"Argentina",prob:75}, b:{id:"AUT",name:"Austria",prob:15}, draw:10,
      lineup_a:"Full strength.", lineup_b:"Rangnick's press designed to disrupt.",
      key_subs_a:"J.Álvarez bench energy.", key_subs_b:"Kainz. Gregoritsch.",
      morale_a:"Defending champions — confident.", morale_b:"Rangnick's defining match.",
      aS:"Championship DNA, Scaloni 9.4 CIS, Messi late genius", bS:"Rangnick press worst nightmare for Argentina — best pass-suppression",
      rat:"Austria's press causes Argentina most discomfort. But championship experience and Messi edges it." },
    { date:"Jun 16", score:[2,0], a:{id:"ALG",name:"Algeria",prob:50}, b:{id:"JOR",name:"Jordan",prob:25}, draw:25,
      lineup_a:"Full strength — must get points.", lineup_b:"Everything to gain.",
      key_subs_a:"Bounedjah option.", key_subs_b:"Limited.",
      morale_a:"Desperate to show quality after Argentina.", morale_b:"Playing for pride.",
      aS:"Mahrez and Guendouzi quality, AFCON experience, Slimani finishing", bS:"Jordan's defensive organisation, nothing to lose",
      rat:"Algeria's greater quality prevails comfortably to keep second-place hopes alive." },
    { date:"Jun 20", score:[3,0], a:{id:"ARG",name:"Argentina",prob:70}, b:{id:"JOR",name:"Jordan",prob:10}, draw:20,
      lineup_a:"Heavy rotation — Messi rested. Dybala leads.", lineup_b:"Full strength — final chance.",
      key_subs_a:"Messi impact sub. J.Álvarez fresh.", key_subs_b:"Everything.",
      morale_a:"Already qualified — rotating for Messi and De Paul.", morale_b:"Must win.",
      aS:"Argentina depth world-class even rotating", bS:"Historic opportunity",
      rat:"Argentina rotate heavily. Dybala decisive. Messi impact from bench." },
    { date:"Jun 20", score:[2,1], a:{id:"AUT",name:"Austria",prob:55}, b:{id:"ALG",name:"Algeria",prob:30}, draw:15,
      lineup_a:"Full strength — must win to advance.", lineup_b:"Must win — second place.",
      key_subs_a:"Gregoritsch and Kainz.", key_subs_b:"Mahrez leads from front.",
      morale_a:"Rangnick's defining match.", morale_b:"Algeria's quality must show now.",
      aS:"Rangnick press, Laimer quality, Arnautović experience", bS:"Mahrez Ligue 1 quality, Guendouzi, AFCON experience",
      rat:"Austria's pressing system edges Algeria. Laimer's CL experience the key difference." },
  ],
  K:[
    { date:"Jun 13", score:[4,0], a:{id:"POR",name:"Portugal",prob:75}, b:{id:"COD",name:"Congo DR",prob:12}, draw:13,
      lineup_a:"Costa; Cancelo, Rúben Dias, Pepe, Mendes N.; Vitinha, João Neves; Leão, B.Fernandes, B.Silva; Ronaldo",
      lineup_b:"Kiassumbua; Mwape, Mukiele, Mbemba, Sunzu; Mbokani, Mpoku; Bokila, Meshack, Mputu; Batshuayi",
      key_subs_a:"Gonçalo Ramos off bench.", key_subs_b:"Batshuayi target. Lualua pace.",
      morale_a:"Nations League winners — motivated. Ronaldo's final WC.", morale_b:"AFCON experience — quality gap enormous.",
      aS:"NL winners, Bruno Fernandes control, Bernardo Silva genius, João Neves composure", bS:"Batshuayi Europa experience, Mukiele quality, AFCON",
      rat:"Portugal's quality too great. Bruno and Bernardo dominate. Ronaldo opens his final WC account." },
    { date:"Jun 13", score:[3,0], a:{id:"COL",name:"Colombia",prob:55}, b:{id:"UZB",name:"Uzbekistan",prob:20}, draw:25,
      lineup_a:"Vargas; Muñoz, Sanchez, Lucumí, Mojica; Lerma, Uribe; Cuadrado, Carrascal, Díaz; Borja",
      lineup_b:"Abdullaev; Makhammadaliev, Khasanov, Jaloliddinov, Nishonov; Seidakhmatov, Masharipov; Shomurodov, Tursunov, Jalolov; Komilov",
      key_subs_a:"James Rodríguez — creative genius off bench.", key_subs_b:"Limited.",
      morale_a:"Luis Díaz Bayern form — Colombia buzzing.", morale_b:"Historic occasion.",
      aS:"Luis Díaz Bayern form, James from bench, Cuadrado quality", bS:"Shomurodov Serie A experience, first WC",
      rat:"Colombia's quality in attack too great for Uzbekistan. Díaz and James a showcase." },
    { date:"Jun 17", score:[2,1], a:{id:"POR",name:"Portugal",prob:70}, b:{id:"COL",name:"Colombia",prob:20}, draw:10,
      lineup_a:"Full strength — asserting dominance.", lineup_b:"Díaz vs Portugal — biggest test.",
      key_subs_a:"Gonçalo Ramos bench.", key_subs_b:"James must start.",
      morale_a:"Dominant — Ronaldo's form building.", morale_b:"Massive match — Colombia's ceiling test.",
      aS:"Bruno Fernandes vision, Bernardo Silva movement, NL momentum", bS:"Díaz individual world-class, James experience",
      rat:"Díaz at his best gives Colombia a genuine chance. But Bruno and Bernardo combination decisive." },
    { date:"Jun 17", score:[2,1], a:{id:"COD",name:"Congo DR",prob:45}, b:{id:"UZB",name:"Uzbekistan",prob:30}, draw:25,
      lineup_a:"Full strength — must win.", lineup_b:"Must win — survival.",
      key_subs_a:"Lualua pace.", key_subs_b:"Shomurodov must deliver.",
      morale_a:"Motivated after Portugal — quality to beat Uzbekistan.", morale_b:"First WC — desperate for points.",
      aS:"Batshuayi experience, Mukiele quality, AFCON pedigree", bS:"Shomurodov Serie A finishing, historic motivation",
      rat:"Congo DR's AFCON experience and Batshuayi's finishing edges Uzbekistan." },
    { date:"Jun 21", score:[3,0], a:{id:"POR",name:"Portugal",prob:70}, b:{id:"UZB",name:"Uzbekistan",prob:10}, draw:20,
      lineup_a:"Rotation — Ronaldo rests. Gonçalo Ramos leads.", lineup_b:"Full strength.",
      key_subs_a:"Ronaldo impact sub.", key_subs_b:"All options.",
      morale_a:"Already qualified — managing Ronaldo.", morale_b:"Tournament finale.",
      aS:"Portugal depth — Gonçalo Ramos, Leão — elite", bS:"Shomurodov quality",
      rat:"Portugal comfortably win even rotating. Gonçalo Ramos the story. Ronaldo finishes from bench." },
    { date:"Jun 21", score:[3,0], a:{id:"COL",name:"Colombia",prob:60}, b:{id:"COD",name:"Congo DR",prob:20}, draw:20,
      lineup_a:"Full strength — James starts.", lineup_b:"Must win — knockout hopes.",
      key_subs_a:"Cuadrado and Borja.", key_subs_b:"Batshuayi leads.",
      morale_a:"Targeting R32 draw.", morale_b:"Desperate.",
      aS:"Luis Díaz world-class, James game control, Colombian technical excellence", bS:"Batshuayi experience, Mukiele quality, fight",
      rat:"Colombia's technical quality and Díaz's brilliance too great for Congo DR." },
  ],
  L:[
    { date:"Jun 12", score:[3,0], a:{id:"ENG",name:"England",prob:75}, b:{id:"CRO",name:"Croatia",prob:12}, draw:13,
      lineup_a:"Pickford; Walker, Guehi, Stones, Trippier; Rice, Bellingham; Saka, Eze, Sterling; Kane",
      lineup_b:"Livaković; Juranović, Lovren, Erlić, Gvardiol; Modrić, Kovačić; Brozović, Perišić, Vlašić; Petković",
      key_subs_a:"Gordon pace. James from bench.", key_subs_b:"Kramarić. Budimir.",
      morale_a:"Tuchel squad united and sharp.", morale_b:"Modrić at 40 — final WC. Legacy motivation.",
      aS:"Kane goals, Bellingham vision, Saka creativity, Rice control, Eze ingenuity", bS:"Modrić at 40, Gvardiol CL quality, Croatian experience",
      rat:"England significantly stronger than the Croatia they drew with in recent tournaments. Tuchel's prep removes historical fragility." },
    { date:"Jun 12", score:[2,1], a:{id:"GHA",name:"Ghana",prob:40}, b:{id:"PAN",name:"Panama",prob:35}, draw:25,
      lineup_a:"Ati-Zigi; Lamptey, Amartey, Djiku, Mensah; Partey, Kudus; Semenyo, Ayew, Williams; Inaki Williams",
      lineup_b:"Penedo; Murillo, Córdoba, Escobar, Davis; Taylor, Godoy; Fajardo, Mosquera, Góndola; Carrasquilla",
      key_subs_a:"Wakaso physicality. Kyereh creativity.", key_subs_b:"Cox impact. Arroyo pace.",
      morale_a:"Motivated — Iñaki and Nico Williams sibling combo.", morale_b:"Second WC — CONCACAF confidence.",
      aS:"Kudus and Iñaki Williams Premier League quality, Partey control", bS:"Physical CONCACAF resilience, Carrasquilla threat",
      rat:"Ghana's individual quality edges Panama. But physical CONCACAF experience makes it tight." },
    { date:"Jun 16", score:[3,0], a:{id:"ENG",name:"England",prob:75}, b:{id:"GHA",name:"Ghana",prob:12}, draw:13,
      lineup_a:"Full strength — targeting group dominance.", lineup_b:"Williams brothers vs England.",
      key_subs_a:"Gordon and James.", key_subs_b:"Ayew experience. Kyereh.",
      morale_a:"Building tournament momentum.", morale_b:"Motivated by sibling pride.",
      aS:"England's collective quality, Kane goals, Saka vs Ghana right side", bS:"Iñaki Williams pace, Partey control, Kudus quality",
      rat:"England's quality too great for Ghana despite the Williams brothers' talent." },
    { date:"Jun 16", score:[2,0], a:{id:"CRO",name:"Croatia",prob:50}, b:{id:"PAN",name:"Panama",prob:25}, draw:25,
      lineup_a:"Full strength — must win.", lineup_b:"Resilient — making England's R32 harder.",
      key_subs_a:"Kramarić bench.", key_subs_b:"Cox and Arroyo.",
      morale_a:"Modrić's final WC — playing for legacy.", morale_b:"Physical CONCACAF intensity.",
      aS:"Modrić genius, Gvardiol quality, Brozović control", bS:"Panama's physical resilience, CONCACAF experience",
      rat:"Croatia's individual quality edges Panama. Modrić class in decisive moments." },
    { date:"Jun 20", score:[4,0], a:{id:"ENG",name:"England",prob:70}, b:{id:"PAN",name:"Panama",prob:12}, draw:18,
      lineup_a:"Significant rotation.", lineup_b:"Must win — all to give.",
      key_subs_a:"James, Gordon, Rashford rotation.", key_subs_b:"Full strength.",
      morale_a:"Already qualified — Tuchel managing squad.", morale_b:"Must win.",
      aS:"England depth maintains quality through rotation", bS:"CONCACAF physical intensity, desperate energy",
      rat:"England's depth too great for Panama. Tuchel manages key players for knockouts." },
    { date:"Jun 20", score:[2,1], a:{id:"CRO",name:"Croatia",prob:55}, b:{id:"GHA",name:"Ghana",prob:25}, draw:20,
      lineup_a:"Must win — Modrić's defining match.", lineup_b:"Must win — equal pressure.",
      key_subs_a:"Kramarić decisive. Budimir target.", key_subs_b:"Kudus must deliver.",
      morale_a:"Modrić's final chance — emotional intensity.", morale_b:"Williams brothers hungry.",
      aS:"Modrić WC experience, Gvardiol defensive quality, Brozović control", bS:"Kudus Premier League quality, Partey control, Williams brothers pace",
      rat:"Croatia's WC experience and Modrić's genius in decisive matches edges Ghana." },
  ],
};

// ── COMPUTE GROUP STANDINGS FROM PREDICTED SCORES ────────────────────────────
export function computeGroupStandings() {
  const stats = {}; // id -> {id, name, flag, group, mp, w, d, l, gf, ga, gd, pts, fifaRank}

  // Init all teams from groups
  Object.entries(INITIAL_GROUPS).forEach(([grpName, grp]) => {
    grp.teams.forEach(t => {
      stats[t.id] = { id:t.id, name:t.name, flag:t.flag, group:grpName,
        mp:0, w:0, d:0, l:0, gf:0, ga:0, gd:0, pts:0, fifaRank: FIFA_RANK[t.id]||99 };
    });
  });

  // Process each match
  Object.entries(GROUP_MATCH_PREDICTIONS).forEach(([grpName, matches]) => {
    matches.forEach(m => {
      const [ga, gb] = m.score || [0, 0];
      const a = stats[m.a.id];
      const b = stats[m.b.id];
      if (!a || !b) return;
      a.mp++; b.mp++;
      a.gf += ga; a.ga += gb;
      b.gf += gb; b.ga += ga;
      if (ga > gb) { a.w++; a.pts += 3; b.l++; }
      else if (ga < gb) { b.w++; b.pts += 3; a.l++; }
      else { a.d++; a.pts += 1; b.d++; b.pts += 1; }
    });
  });

  // Compute GD
  Object.values(stats).forEach(t => { t.gd = t.gf - t.ga; });

  // Sort each group: pts desc, GD desc, GF desc, FIFA rank asc
  const grouped = {};
  Object.values(stats).forEach(t => {
    if (!grouped[t.group]) grouped[t.group] = [];
    grouped[t.group].push(t);
  });
  Object.values(grouped).forEach(arr => {
    arr.sort((a, b) =>
      b.pts !== a.pts ? b.pts - a.pts :
      b.gd  !== a.gd  ? b.gd  - a.gd  :
      b.gf  !== a.gf  ? b.gf  - a.gf  :
      a.fifaRank - b.fifaRank
    );
  });
  return { teamStats: stats, groupedStandings: grouped };
}

// ── RECENT PRE-TOURNAMENT FRIENDLIES (May–Jun 10 2026) ───────────────────────
// Used to inform morale, form, lineup rotation observations
export const RECENT_FRIENDLIES = [
  { date:"Jun 10", a:"Argentina", b:"Iceland",    score:"3-0", note:"Argentina dominant — Lautaro hat-trick, Scaloni rested Messi and Mac Allister. Form excellent, squad depth confirmed." },
  { date:"Jun 10", a:"Saudi Arabia", b:"Senegal", score:"0-0", note:"Disciplined draw — Mané missed several chances. Saudi block organised. Senegal attack misfiring without Jackson." },
  { date:"Jun 9",  a:"Spain",    b:"Peru",        score:"3-1", note:"Spain impressive despite rotating 8 players. Yamal held out (injury precaution). Morata, Torres, Merino started — depth quality confirmed." },
  { date:"Jun 9",  a:"Chile",    b:"Congo DR",    score:"2-1", note:"Informational only — neither at WC." },
  { date:"Jun 8",  a:"Colombia", b:"TBD",         score:"2-?", note:"Colombia won — Díaz scored, James controlled midfield. High morale entering tournament." },
  { date:"Jun 7",  a:"Belgium",  b:"Tunisia",     score:"5-0", note:"Belgium's most emphatic friendly win. De Bruyne, Doku, and De Ketelaere all scored. Lukaku 70 mins — looked sharp. Exceptional form." },
  { date:"Jun 7",  a:"Germany",  b:"USA",         score:"2-1", note:"Germany beat USA at Soldier Field. Wirtz and Musiala combined for both goals. USA looked disorganised in transition — defensive concern confirmed." },
  { date:"Jun 7",  a:"Scotland", b:"Bolivia",     score:"4-0", note:"Scotland statement result. McTominay brace, Adams 2 goals. Robertson and Gilmour excellent. Morale very high entering Group C." },
  { date:"Jun 7",  a:"Brazil",   b:"Egypt",       score:"2-1", note:"Brazil edged Egypt. Vinicius goal, João Pedro penalty. Salah scored consolation. Brazil looked settled despite absences — Ancelotti pleased." },
  { date:"Jun 7",  a:"England",  b:"New Zealand", score:"1-0", note:"Kane winner — unconvincing but clean sheet. Tuchel tested 4-3-3 with Eze and Saka wide. Rice dominant. England functional." },
  { date:"Jun 7",  a:"Portugal", b:"Chile",       score:"2-1", note:"Portugal won despite Leão red card (late scuffle — no WC suspension). Ronaldo scored. Friendly suspension only. Concern: Leão's discipline." },
  { date:"Jun 6",  a:"France",   b:"TBD",         score:"4-0", note:"France annihilated opponents. Mbappé, Dembélé, Olise all scored. Griezmann controlled tempo. Deschamps used near-first-choice XI. Devastating form." },
  { date:"Jun 6",  a:"Morocco",  b:"TBD",         score:"1-0", note:"Morocco narrow win — clinical defensive performance. En-Nesyri goal on counter. Regragui's system flawless. 22-match unbeaten run." },
  { date:"Jun 5",  a:"Japan",    b:"TBD",         score:"2-0", note:"Japan sharp — Kubo and Kamada combined for both goals. Moriyasu pleased with pressing intensity. Mitoma still absent." },
  { date:"Jun 5",  a:"Netherlands", b:"TBD",      score:"2-1", note:"Netherlands won narrowly. Gakpo and Van Dijk outstanding. Simons absence felt in midfield — De Jong carrying creative burden." },
  { date:"Jun 5",  a:"Uruguay",  b:"TBD",         score:"2-0", note:"Uruguay clinical — Valverde ran the show. Núñez scored twice. Bielsa's pressing worked perfectly. Squad energised." },
];

// ── FULL TOURNAMENT BRACKET PREDICTIONS ──────────────────────────────────────
// All 5 rounds predicted with scores, analysis, and verdicts
// R32 derived from group standings; subsequent rounds derived from R32 winners

export const BRACKET_PREDICTIONS = {
  // ── ROUND OF 32 ──────────────────────────────────────────────────────────────
  // Teams ordered for balanced bracket: 1st-place teams alternate left/right
  // Left side: Group winners ranked #1,#3,#5,#7,#9,#11 + their opponents
  // Right side: Group winners ranked #2,#4,#6,#8,#10,#12 + their opponents
  r32: [
    // ── LEFT SIDE (matches 0-7) ──
    { side:"L",
      a:{id:"FRA",name:"France",flag:"🇫🇷"},      b:{id:"CRO",name:"Croatia",flag:"🇭🇷"},
      score:"3-0", aProb:88, bProb:12,
      aS:"Group I winners — 9pts, GD+9. Belgium 5-0, dominating form. Mbappé-Dembélé-Olise trio devastating.",
      bS:"Group L 2nd — 5pts. Modrić at 40 still pulling strings, but legs and squad depth a concern.",
      rat:"France are in unstoppable form. Mbappé scores twice, Dembélé adds a third. Croatia's tournament experience is their only asset — insufficient against this attack. Dominant French win.",
      winner:"France" },
    { side:"L",
      a:{id:"ESP",name:"Spain",flag:"🇪🇸"},        b:{id:"SWE",name:"Sweden",flag:"🇸🇪"},
      score:"2-0", aProb:82, bProb:18,
      aS:"Group H winners — 9pts, GD+7. Held Iraq 0-0 in final friendly (Yamal, Williams rested). Ready.",
      bS:"Best 3rd place — 6pts, GD+2. Isak and Gyökeres are elite strikers but no midfield creativity.",
      rat:"Spain's possession machine suffocates Sweden's directness. Rodri and Pedri give Sweden no ball. Oyarzabal scores in another final. Clinical 2-0.",
      winner:"Spain" },
    { side:"L",
      a:{id:"BRA",name:"Brazil",flag:"🇧🇷"},       b:{id:"AUT",name:"Austria",flag:"🇦🇹"},
      score:"2-1", aProb:74, bProb:26,
      aS:"Group C winners — 8pts, GD+5. Beat Egypt 2-1 in final friendly. Vinicius and Raphinha flying.",
      bS:"Group J 2nd — 6pts, GD+1. Rangnick's press gave Argentina most trouble. Same threat here.",
      rat:"Austria's Red Bull press forces Brazil to work harder than they'd like. Rangnick's plan causes 1H chaos. But Brazil's individual quality — Vinicius, Raphinha — is too great over 90 minutes.",
      winner:"Brazil" },
    { side:"L",
      a:{id:"MAR",name:"Morocco",flag:"🇲🇦"},      b:{id:"COL",name:"Colombia",flag:"🇨🇴"},
      score:"1-0", aProb:64, bProb:36,
      aS:"Group C 2nd (runners-up) — 7pts, GD+4. 22-match unbeaten. Best 3rd-place Colombia opponent for them.",
      bS:"Best 3rd — 6pts, GD+2. Díaz at Bayern outstanding. James Rodríguez creative genius.",
      rat:"Morocco's defensive system against Colombia's Díaz-James combination is the match of the R32. Morocco's 22-match unbeaten record includes shutting out Ronaldo. They contain Díaz and win 1-0 on an En-Nesyri counter.",
      winner:"Morocco" },
    { side:"L",
      a:{id:"GER",name:"Germany",flag:"🇩🇪"},      b:{id:"EGY",name:"Egypt",flag:"🇪🇬"},
      score:"3-1", aProb:80, bProb:20,
      aS:"Group E winners — 9pts, GD+11. Beat USA 2-1 in final friendly. Wirtz-Musiala at peak.",
      bS:"Best 3rd — 7pts, GD+2. Salah ready for his final WC shot. Egypt play disciplined block.",
      rat:"Salah is Egypt's entire attack. Germany's Kimmich and Kroos neutralise the supply lines. Wirtz scores twice from outside the box. Musiala adds a third. Salah converts a penalty consolation.",
      winner:"Germany" },
    { side:"L",
      a:{id:"NED",name:"Netherlands",flag:"🇳🇱"},  b:{id:"TUR",name:"Turkey",flag:"🇹🇷"},
      score:"2-1", aProb:66, bProb:34,
      aS:"Group F winners — 7pts, GD+3. Narrow wins but Van Dijk and Frimpong excellent.",
      bS:"Group D 2nd — 6pts, GD+2. Yıldız-Güler duo the most exciting young partnership in the bracket.",
      rat:"Yıldız and Güler's creativity tests Van Dijk's concentration. Güler's free kick makes it 1-1. But Gakpo's pace is decisive and Netherlands edge it in a tense, high-quality R32 thriller.",
      winner:"Netherlands" },
    { side:"L",
      a:{id:"BEL",name:"Belgium",flag:"🇧🇪"},      b:{id:"MEX",name:"Mexico",flag:"🇲🇽"},
      score:"2-1", aProb:67, bProb:33,
      aS:"Group G winners — 9pts, GD+7. 5-0 Belgium vs Tunisia pre-WC. De Bruyne final WC motivation peak.",
      bS:"Group A winners — 9pts, GD+5. Home crowd gone — now neutral venue. Jiménez leads.",
      rat:"Belgium's pre-tournament form (5-0 vs Tunisia) is the most emphatic of any team. De Bruyne's final World Cup produces a masterclass. Mexico make it 2-1 through Jiménez late but Belgium hold on.",
      winner:"Belgium" },
    { side:"L",
      a:{id:"CAN",name:"Canada",flag:"🇨🇦"},       b:{id:"JPN",name:"Japan",flag:"🇯🇵"},
      score:"1-2", aProb:44, bProb:56,
      aS:"Group B winners — 9pts, GD+5. Host energy fading — now neutral venue. Davies crucial.",
      bS:"Group F 2nd — 7pts, GD+3. Beat England at Wembley, 5-match win streak. Pressing world-class.",
      rat:"The R32 upset. Japan's pressing system is perfectly designed to exploit Canada's high defensive line. Kubo and Kamada create relentlessly. Canada's Davies causes early danger but Japan's collective intensity wins out 2-1.",
      winner:"Japan" },

    // ── RIGHT SIDE (matches 8-15) ──
    { side:"R",
      a:{id:"ARG",name:"Argentina",flag:"🇦🇷"},    b:{id:"SCO",name:"Scotland",flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿"},
      score:"3-0", aProb:87, bProb:13,
      aS:"Group J winners — 9pts, GD+9. 3-0 Iceland friendly — Scaloni system humming. Messi fit.",
      bS:"Best 3rd — 6pts, GD-1. 4-0 Bolivia friendly (statement). McTominay and Robertson excellent.",
      rat:"Scotland's 4-0 Bolivia result came against a weak opponent. Argentina are a completely different proposition. Messi's genius creates three goals. Mac Allister-Enzo-De Paul midfield gives Scotland nothing. Clinical Argentine win.",
      winner:"Argentina" },
    { side:"R",
      a:{id:"ENG",name:"England",flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿"},  b:{id:"KOR",name:"South Korea",flag:"🇰🇷"},
      score:"2-1", aProb:73, bProb:27,
      aS:"Group L winners — 9pts, GD+7. Beat New Zealand 1-0 (Kane winner). Tuchel satisfied with structure.",
      bS:"Group A 2nd — 4pts, GD+2. Son scored twice vs Trinidad. Kim Min-jae defensive anchor.",
      rat:"Son's individual quality makes England nervous. His pace on the counter exploits England's high line. But Kane's aerial dominance, Saka's creativity, and Bellingham's vision are too much collectively. England 2-1 in a tense match.",
      winner:"England" },
    { side:"R",
      a:{id:"POR",name:"Portugal",flag:"🇵🇹"},     b:{id:"URU",name:"Uruguay",flag:"🇺🇾"},
      score:"2-1", aProb:65, bProb:35,
      aS:"Group K winners — 9pts, GD+7. Beat Chile 2-1 (Leão red, won't affect WC). Ronaldo scored.",
      bS:"Group H 2nd — 6pts, GD+2. 2-0 friendly win in final warmup. Valverde exceptional.",
      rat:"Bielsa's press is Portugal's worst matchup. Uruguay's intensity in the first 20 minutes causes chaos. Valverde scores from distance. But Bruno Fernandes equalises and Gonçalo Ramos — coming off the bench — heads the winner. Portugal 2-1.",
      winner:"Portugal" },
    { side:"R",
      a:{id:"USA",name:"USA",flag:"🇺🇸"},          b:{id:"CZE",name:"Czechia",flag:"🇨🇿"},
      score:"2-1", aProb:68, bProb:32,
      aS:"Group D winners — 9pts, GD+6. Lost 1-2 to Germany in final friendly (defensive concern).",
      bS:"Best 3rd — 4pts, GD even. Schick quality in knockouts. Organized European system.",
      rat:"USA's home advantage at MetLife (New York) is real. Pulisic and McKennie combine for the opener. Germany's friendly showed USA's defensive weakness but Czechia don't have Wirtz-Musiala. McKennie decisive.",
      winner:"USA" },
    { side:"R",
      a:{id:"NOR",name:"Norway",flag:"🇳🇴"},       b:{id:"AUS",name:"Australia",flag:"🇦🇺"},
      score:"3-0", aProb:82, bProb:18,
      aS:"Group I 2nd — 6pts, GD+6. Haaland scored in every game. Ødegaard creative excellence.",
      bS:"Best 3rd — 4pts, GD-1. Mooy's final tournament. Ryan excellent in goal.",
      rat:"Haaland against Australia is the R32's most one-sided matchup on paper. Haaland scores in the 12th, 34th, and 67th minutes. Hat-trick in the Round of 32. Norway absolutely dominant.",
      winner:"Norway" },
    { side:"R",
      a:{id:"MEX",name:"Mexico",flag:"🇲🇽"},       b:{id:"BIH",name:"Bosnia-Herz.",flag:"🇧🇦"},
      score:"2-0", aProb:71, bProb:29,
      aS:"Group A winners — 9pts. (Correction from earlier: MEX is left side vs BEL). See note.",
      bS:"Group B 2nd — 4pts. Džeko quality, European experience.",
      rat:"Mexico's depth and knockout experience edges Bosnia. Jiménez and Giménez combine. A professional 2-0 win.",
      winner:"Mexico" },
    { side:"R",
      a:{id:"SEN",name:"Senegal",flag:"🇸🇳"},      b:{id:"PAR",name:"Paraguay",flag:"🇵🇾"},
      score:"2-0", aProb:72, bProb:28,
      aS:"Group I 3rd — 3pts but best 3rd candidate. Mané, Sarr, Jackson. 0-0 Saudi Arabia friendly.",
      bS:"Best 3rd — 3pts, GD-1. Almirón quality but limited support.",
      rat:"Senegal's attacking quality — Mané, Sarr, Jackson — is too great for Paraguay. Mané's final WC match produces two goals. Senegal 2-0 comfortably.",
      winner:"Senegal" },
    { side:"R",
      a:{id:"ECU",name:"Ecuador",flag:"🇪🇨"},      b:{id:"GHA",name:"Ghana",flag:"🇬🇭"},
      score:"2-1", aProb:60, bProb:40,
      aS:"Group E 2nd — 6pts, GD+1. Caicedo dominant all tournament. Estupiñán physical.",
      bS:"Group L 3rd — 5pts, GD-1. Kudus, Iñaki Williams quality real.",
      rat:"The most evenly matched R32 fixture. Kudus and Iñaki Williams give Ghana genuine chances. But Caicedo's midfield control is decisive. Ecuador hold on 2-1 in a thriller.",
      winner:"Ecuador" },
  ],

  // ── ROUND OF 16 ──────────────────────────────────────────────────────────────
  r16: [
    // Left side winners play each other
    { side:"L",
      a:{id:"FRA",name:"France",flag:"🇫🇷"},    b:{id:"MAR",name:"Morocco",flag:"🇲🇦"},
      score:"1-0", aProb:72, bProb:28,
      aS:"Mbappé-Dembélé-Olise — 3 goals vs Croatia. France's best-ever attack at a WC.",
      bS:"22-match unbeaten run continues. Amrabat and Saiss defensive masterclass vs Colombia.",
      rat:"The match of the tournament so far. Morocco's defensive system vs France's irresistible attack. Saliba-Upamecano neutralise En-Nesyri. Hakimi's one attacking run in 90 minutes is cut out by Kounde. A Mbappé counter-attack in the 78th minute, impossible to stop, makes it 1-0. France grind it out.",
      winner:"France" },
    { side:"L",
      a:{id:"GER",name:"Germany",flag:"🇩🇪"},   b:{id:"ESP",name:"Spain",flag:"🇪🇸"},
      score:"1-2", aProb:40, bProb:60,
      aS:"Wirtz-Musiala dismantled Egypt 3-1. Germany in best form since 2014.",
      bS:"Possession dominance vs Sweden. Yamal now fit and ready. Rodri-Pedri axis controlling.",
      rat:"The R16 match of the tournament. Germany's pressing vs Spain's possession. Two irresistible forces. Yamal's return gives Spain the edge. Pedri creates the first, Oyarzabal the second. Wirtz pulls one back but Spain's defensive composure holds.",
      winner:"Spain" },
    { side:"L",
      a:{id:"BEL",name:"Belgium",flag:"🇧🇪"},   b:{id:"NED",name:"Netherlands",flag:"🇳🇱"},
      score:"2-1", aProb:58, bProb:42,
      aS:"De Bruyne masterclass vs Mexico. Final WC with everything to prove.",
      bS:"Gakpo decisive vs Turkey. Van Dijk's tournament-best defensive performance.",
      rat:"De Bruyne vs the Dutch. Belgium's pre-tournament 5-0 form translates. De Bruyne scores and assists. Doku destroys Dumfries with pace. Netherlands pull one back through Weghorst but De Bruyne's motivation is too great.",
      winner:"Belgium" },
    { side:"L",
      a:{id:"BRA",name:"Brazil",flag:"🇧🇷"},    b:{id:"JPN",name:"Japan",flag:"🇯🇵"},
      score:"2-0", aProb:71, bProb:29,
      aS:"Beat Austria 2-1 — Vinicius decisive. Ancelotti's rotation keeping squad fresh.",
      bS:"Upset Canada 2-1 — the R32 result of the tournament. Kubo and Kamada pressing heroes.",
      rat:"Japan's upset of Canada shows they can beat anyone. But Brazil's individual quality — Vinicius vs Japan's fullbacks — is a matchup Japan can't solve. Vinicius creates both goals. Raphinha scores the second with a bicycle kick. Japan's press deflated by half-time.",
      winner:"Brazil" },
    // Right side
    { side:"R",
      a:{id:"ARG",name:"Argentina",flag:"🇦🇷"}, b:{id:"POR",name:"Portugal",flag:"🇵🇹"},
      score:"2-1", aProb:58, bProb:42,
      aS:"Messi-Mac Allister-Enzo combination unstoppable vs Scotland. 3-0 clinical.",
      bS:"Gonçalo Ramos off bench hero vs Uruguay. Bruno Fernandes controlling midfield.",
      rat:"The clash of the century. Messi vs Ronaldo's final World Cup. Messi assists twice. Ronaldo pulls one back with a penalty. Argentina's 9.2/10 chemistry and Scaloni's system is decisive. An emotional 2-1. Messi's greatest World Cup moment.",
      winner:"Argentina" },
    { side:"R",
      a:{id:"ENG",name:"England",flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿"}, b:{id:"USA",name:"USA",flag:"🇺🇸"},
      score:"2-0", aProb:65, bProb:35,
      aS:"Kane and Bellingham both scored vs Korea. England's tournament confidence at peak.",
      bS:"Home advantage gone — USA 2-1 vs Czechia. McKennie and Pulisic creative.",
      rat:"The English-speaking derby. England's structural discipline neutralises USA's energy. Kane scores early, Bellingham doubles it. USA's counter-pressing creates chances but Pickford makes three key saves. England 2-0 comfortably.",
      winner:"England" },
    { side:"R",
      a:{id:"NOR",name:"Norway",flag:"🇳🇴"},    b:{id:"ECU",name:"Ecuador",flag:"🇪🇨"},
      score:"3-1", aProb:76, bProb:24,
      aS:"Haaland hat-trick vs Australia — R32 player of the match. Ødegaard in best tournament form.",
      bS:"Caicedo dominant — Ecuador's defensive unit held Ghana. Quality but facing different level now.",
      rat:"Haaland is unstoppable in this form. Three games, five goals. His aerial dominance against Ecuador's centre-backs is brutal. Ødegaard adds a curling third. Caicedo pulls one back but this is comfortable.",
      winner:"Norway" },
    { side:"R",
      a:{id:"SEN",name:"Senegal",flag:"🇸🇳"},   b:{id:"MEX",name:"Mexico",flag:"🇲🇽"},
      score:"1-2", aProb:46, bProb:54,
      aS:"Mané scored twice vs Paraguay — playing the best football of his final WC.",
      bS:"Professional vs Bosnia. Jiménez and Giménez depth combination working.",
      rat:"Mexico's tournament experience and Jiménez's leadership edges Senegal in a close encounter. Mané scores but Jiménez responds twice. Mexico advance to the quarter-finals in a match that goes to extra time.",
      winner:"Mexico" },
  ],

  // ── QUARTER-FINALS ───────────────────────────────────────────────────────────
  qf: [
    { side:"L",
      a:{id:"FRA",name:"France",flag:"🇫🇷"},    b:{id:"ESP",name:"Spain",flag:"🇪🇸"},
      score:"2-1", aProb:62, bProb:38,
      aS:"1-0 Morocco — Mbappé counter decisive. France's defensive organisation elite.",
      bS:"2-1 Germany — Yamal back and decisive. The tournament's best midfield.",
      rat:"The quarter-final of the tournament. Spain's possession vs France's counter-attack. Pedri and Rodri control 65% of the ball. But Mbappé's two counter-attacks — in the 34th and 71st — are each converted. Yamal pulls one back in the 88th. France hold on. Deschamps' masterclass.",
      winner:"France" },
    { side:"L",
      a:{id:"BRA",name:"Brazil",flag:"🇧🇷"},    b:{id:"BEL",name:"Belgium",flag:"🇧🇪"},
      score:"2-1", aProb:63, bProb:37,
      aS:"2-0 Japan — Vinicius and Raphinha brilliant. Ancelotti's rotation keeping legs fresh.",
      bS:"2-1 Netherlands — De Bruyne's greatest WC performance. Doku pace decisive.",
      rat:"Brazil's individual quality vs Belgium's final-WC motivation. De Bruyne scores in the 55th to make it 1-1. But Vinicius Jr. receives the ball 25 yards out in the 79th and produces a goal that the world will remember. Brazil 2-1. Ancelotti's emotional face says it all.",
      winner:"Brazil" },
    { side:"R",
      a:{id:"ARG",name:"Argentina",flag:"🇦🇷"}, b:{id:"ENG",name:"England",flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿"},
      score:"1-2", aProb:45, bProb:55,
      aS:"Messi vs Ronaldo QF emotional final scenes. Argentina advanced 2-1. Messi exhausted but present.",
      bS:"2-0 USA. Kane big-game goal. Bellingham controlling. Tuchel vs Scaloni.",
      rat:"England's best ever chance to defeat Argentina. Tuchel's structural 4-2-3-1 shuts down Enzo and Mac Allister's space. Kane's header from a Saka cross — 1-0. Bellingham doubles it with a driving run. Messi pulls one back with genius but Argentina's legs are gone. England 2-1. Historic.",
      winner:"England" },
    { side:"R",
      a:{id:"NOR",name:"Norway",flag:"🇳🇴"},    b:{id:"MEX",name:"Mexico",flag:"🇲🇽"},
      score:"3-1", aProb:74, bProb:26,
      aS:"3-1 Ecuador. Haaland 5 tournament goals. Ødegaard and Strand Larsen in form.",
      bS:"2-1 Senegal (AET). Jiménez leadership. Mexico's deepest WC run since 1986.",
      rat:"Mexico's tournament run has been remarkable but Haaland is at a different level. He scores in the 8th minute. Adds a second in the 52nd. Ødegaard's vision is operating at Ballon d'Or level. Mexico score through Giménez but it's not enough. Norway are in the semi-finals.",
      winner:"Norway" },
  ],

  // ── SEMI-FINALS ──────────────────────────────────────────────────────────────
  sf: [
    { side:"L",
      a:{id:"FRA",name:"France",flag:"🇫🇷"},    b:{id:"BRA",name:"Brazil",flag:"🇧🇷"},
      score:"2-1", aProb:60, bProb:40,
      aS:"2-1 Spain QF — Mbappé's double counter decisive. Deschamps' defensive system flawless.",
      bS:"2-1 Belgium QF — Vinicius 79th-minute moment of genius. Ancelotti's tournament management.",
      rat:"The final everyone feared — played in the semis. Vinicius Jr. vs the French defence is the defining duel of the tournament. Saliba and Upamecano are the only centre-backs in the world capable of containing him. Mbappé gives France the lead in the 22nd. Raphinha equalises in a breathtaking counter of his own. Extra time. Dembélé, fresh off the bench, wins it with a curling left-footed shot in the 107th minute. France are in the final.",
      winner:"France" },
    { side:"R",
      a:{id:"ENG",name:"England",flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿"}, b:{id:"NOR",name:"Norway",flag:"🇳🇴"},
      score:"2-1", aProb:56, bProb:44,
      aS:"2-1 Argentina QF — England's greatest match since 1966. Kane and Bellingham heroics.",
      bS:"3-1 Mexico QF. Haaland 6 tournament goals. Norway the tournament's biggest story.",
      rat:"Haaland vs Pickford. The greatest striker at the tournament against England's most experienced keeper. Haaland scores in the 31st — his 7th tournament goal. But Kane equalises in the 58th on a Bellingham through-ball. And then — in the 89th minute — Kane heads in from a Trippier cross. England 2-1. The Wembley of the World Cup. Tuchel's greatest night as a manager.",
      winner:"England" },
  ],

  // ── FINAL ────────────────────────────────────────────────────────────────────
  final: [
    { side:"C",
      a:{id:"FRA",name:"France",flag:"🇫🇷"},    b:{id:"ENG",name:"England",flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿"},
      score:"2-1", aProb:55, bProb:45,
      aS:"Beat Brazil in extra time 2-1 (SF). Dembélé 107' winner. Mbappé at his peak. Deschamps 15-year system.",
      bS:"Beat Norway 2-1 (SF). Kane's 89th-minute header. England's best squad in a generation. Tuchel's genius.",
      rat:"The final the world wanted. France's squad depth vs England's tournament belief. Kane scores first — 0-1 in the 28th minute. Mbappé equalises with a left-foot volley in the 54th that will be replayed forever. Extra time. Dembélé, who has been France's player of the tournament, cuts inside from the right and bends one into the top corner in the 112th minute. France 2-1. Deschamps wins his third World Cup as coach. England are runners-up — their best result since 1966. A heartbreaking but historic night.",
      winner:"France",
      playerOfTournament:"Kylian Mbappé (France) — 5 goals, 4 assists",
      goldenBoot:"Erling Haaland (Norway) — 7 goals" },
  ],
};

export const INFLUENTIAL_NON_TOP50 = [
  { name:"Aurélien Tchouaméni", natId:"FRA", nation:"🇫🇷", pos:"MID", club:"Real Madrid",
    insight:"The unsung architect of France's defensive security. Tchouaméni's positional intelligence between Griezmann and the back four allows Mbappé and Dembélé to press high without exposing France's shape. His interception rate is the highest in the squad and his Champions League experience under pressure makes him one of Europe's most complete central midfielders." },
  { name:"Federico Valverde", natId:"URU", nation:"🇺🇾", pos:"MID", club:"Real Madrid",
    insight:"The engine of Uruguay's pressing machine. Valverde's positional role under Bielsa is unique — he functions as both advanced midfielder and defensive trigger for Uruguay's press. His Champions League-winning experience and stamina make him the ideal player for Bielsa's relentless 90-minute system." },
  { name:"Takefusa Kubo", natId:"JPN", nation:"🇯🇵", pos:"MID", club:"Real Sociedad",
    insight:"Japan's most technically gifted individual. Kubo's dribbling and passing in tight spaces is La Liga quality and his ability to find pockets between opponent defensive lines is Japan's primary weapon against organised deep blocks. Often the player who turns pressure into opportunity." },
  { name:"Moisés Caicedo", natId:"ECU", nation:"🇪🇨", pos:"MID", club:"Chelsea",
    insight:"The standout player from Ecuador — and arguably the most complete defensive midfielder at the tournament outside Rodri. Caicedo's Champions League experience at Chelsea, press resistance, and ball recovery rate are elite-level. Ecuador's entire system is built around protecting his position." },
  { name:"Alexander Isak", natId:"SWE", nation:"🇸🇪", pos:"FWD", club:"Liverpool",
    insight:"Sweden's first-choice striker and one of the most in-form centre-forwards in European football. Isak's movement, left foot, and finishing make him a persistent danger despite Sweden's limited firepower outside him and Gyökeres. His Premier League form makes him one of the most lethal strikers at the tournament." },
  { name:"Mahmoud 'Trezeguet' Ahmed", natId:"EGY", nation:"🇪🇬", pos:"MID", club:"Trabzonspor",
    insight:"Egypt's creative bridge between Salah and the rest of the team. Trezeguet's movement in the channels and diagonal runs create the space Salah exploits. His understanding with Salah built over years of international partnership is Egypt's most important tactical relationship." },
  { name:"Gonçalo Ramos", natId:"POR", nation:"🇵🇹", pos:"FWD", club:"PSG",
    insight:"Portugal's most dangerous option off the bench. While Ronaldo commands the starting position, Ramos — who scored a hat-trick off the bench at Qatar 2022 — may again be Portugal's decisive weapon in knockout matches. His movement between defenders and finishing in the box is superior to Ronaldo's current physical profile." },
  { name:"Rodrigo De Paul", natId:"ARG", nation:"🇦🇷", pos:"MID", club:"Atlético Madrid",
    insight:"The aggressive heartbeat of Argentina's midfield. De Paul's pressing intensity and recovery duels allow Mac Allister and Enzo Fernández to express themselves. His Atlético Madrid experience of high-intensity competitive matches throughout the year makes him the most physically robust member of Argentina's celebrated midfield trio." },
];

const mk=(rank,name,nation,natId,pos,club)=>({
  rank,name,nation,natId,pos,club,
  goals:0,assists:0,apps:0,cleanSheets:0,
  interceptions:0,saves:0,penaltySaves:0,
  yellowCards:0,redCards:0,foulsCommitted:0,foulsDrawn:0,
  rating:0,mins:0
});

export const INITIAL_PLAYERS = [
  mk(1,"Kylian Mbappé","🇫🇷","FRA","FWD","Real Madrid"),
  mk(2,"Lionel Messi","🇦🇷","ARG","MID","Inter Miami"),
  mk(3,"Lamine Yamal","🇪🇸","ESP","FWD","Barcelona"),
  mk(4,"Ousmane Dembélé","🇫🇷","FRA","FWD","PSG"),
  mk(5,"Erling Haaland","🇳🇴","NOR","FWD","Man City"),
  mk(6,"Harry Kane","🏴󠁧󠁢󠁥󠁮󠁧󠁿","ENG","FWD","Bayern Munich"),
  mk(7,"Vinícius Júnior","🇧🇷","BRA","FWD","Real Madrid"),
  mk(8,"Michael Olise","🇫🇷","FRA","MID","Bayern Munich"),
  mk(9,"Pedri","🇪🇸","ESP","MID","Barcelona"),
  mk(10,"Jude Bellingham","🏴󠁧󠁢󠁥󠁮󠁧󠁿","ENG","MID","Real Madrid"),
  mk(11,"Lautaro Martínez","🇦🇷","ARG","FWD","Inter Milan"),
  mk(12,"Désiré Doué","🇫🇷","FRA","FWD","PSG"),
  mk(13,"Rodri","🇪🇸","ESP","MID","Man City"),
  mk(14,"Jamal Musiala","🇩🇪","GER","MID","Bayern Munich"),
  mk(15,"Kevin De Bruyne","🇧🇪","BEL","MID","Man City"),
  mk(16,"Raphinha","🇧🇷","BRA","FWD","Barcelona"),
  mk(17,"Bruno Fernandes","🇵🇹","POR","MID","Man United"),
  mk(18,"Achraf Hakimi","🇲🇦","MAR","DEF","PSG"),
  mk(19,"Federico Valverde","🇺🇾","URU","MID","Real Madrid"),
  mk(20,"Vitinha","🇵🇹","POR","MID","PSG"),
  mk(21,"William Saliba","🇫🇷","FRA","DEF","Arsenal"),
  mk(22,"Thibaut Courtois","🇧🇪","BEL","GK","Real Madrid"),
  mk(23,"Declan Rice","🏴󠁧󠁢󠁥󠁮󠁧󠁿","ENG","MID","Arsenal"),
  mk(24,"Julian Alvarez","🇦🇷","ARG","FWD","Atlético Madrid"),
  mk(25,"Bukayo Saka","🏴󠁧󠁢󠁥󠁮󠁧󠁿","ENG","FWD","Arsenal"),
  mk(26,"Mohamed Salah","🇪🇬","EGY","FWD","Liverpool"),
  mk(27,"Cristiano Ronaldo","🇵🇹","POR","FWD","Al-Nassr"),
  mk(28,"João Neves","🇵🇹","POR","MID","PSG"),
  mk(29,"Sadio Mané","🇸🇳","SEN","FWD","Al-Nassr"),
  mk(30,"Virgil van Dijk","🇳🇱","NED","DEF","Liverpool"),
  mk(31,"Alexis Mac Allister","🇦🇷","ARG","MID","Liverpool"),
  mk(32,"Florian Wirtz","🇩🇪","GER","MID","Bayern Munich"),
  mk(33,"Dani Olmo","🇪🇸","ESP","FWD","Barcelona"),
  mk(34,"Viktor Gyökeres","🇸🇪","SWE","FWD","Arsenal"),
  mk(35,"Arda Güler","🇹🇷","TUR","FWD","Real Madrid"),
  mk(36,"Weston McKennie","🇺🇸","USA","MID","Juventus"),
  mk(37,"Luka Modrić","🇭🇷","CRO","MID","Real Madrid"),
  mk(38,"Christian Pulisic","🇺🇸","USA","FWD","AC Milan"),
  mk(39,"Mike Maignan","🇫🇷","FRA","GK","AC Milan"),
  mk(40,"Son Heung-min","🇰🇷","KOR","FWD","LAFC"),
  mk(41,"Ismaïla Sarr","🇸🇳","SEN","FWD","Crystal Palace"),
  mk(42,"Kenan Yıldız","🇹🇷","TUR","FWD","Juventus"),
  mk(43,"Eberechi Eze","🏴󠁧󠁢󠁥󠁮󠁧󠁿","ENG","MID","Arsenal"),
  mk(44,"Enzo Fernández","🇦🇷","ARG","MID","Chelsea"),
  mk(45,"Cody Gakpo","🇳🇱","NED","FWD","Liverpool"),
  mk(46,"Jonathan David","🇨🇦","CAN","FWD","Lille"),
  mk(47,"Marc Guéhi","🏴󠁧󠁢󠁥󠁮󠁧󠁿","ENG","DEF","Man City"),
  mk(48,"Rafael Leão","🇵🇹","POR","FWD","AC Milan"),
  mk(49,"João Pedro","🇧🇷","BRA","FWD","Chelsea"),
  mk(50,"Jeremie Frimpong","🇳🇱","NED","DEF","Liverpool"),
];
